export const states = [
  {
    name: "Amazonas",
    agencies: [
      {
        id: "2RALMuqDz1",
        city: "Puerto Ayacucho",
        name: "MRW PUERTO AYACUCHO",
        address: "Avenida Principal De La Urbanizacion Andres Eloy Blanco, Edificio Bellmar, Local Nro 1. Codigo Postal 7101.",
        code: "0200000",
      },
    ]
  },
  {
    name: "Anzoátegui",
    agencies: [
      {
        id: "hbKFqChkR1",
        city: "Anaco",
        name: "MRW ANACO",
        address: "Av. Jose Antonio Anzoategui, C.c. Anaco Center, Local 79-c. Anaco Edo. Anzoategui.",
        code: "0301000",
      },
      {
        id: "hbKFqChkR2",
        city: "Barcelona",
        name: "MRW BARCELONA",
        address: "Av. Fuerzas Armadas. Esquina Calle Eulalia Buroz, Edif Azgan Piso Pb Local 02 Sector Centro.",
        code: "0300000",
      },
      {
        id: "hbKFqChkR3",
        city: "Barcelona",
        name: "MRW NUEVA BARCELONA",
        address: "Prolong. Av. Fuerzas Armadas. C.c. Los Chaguaramos Local 4, Sector Nueva Barcelona, Anzoategui.",
        code: "0310000",
      },
      {
        id: "hbKFqChkR4",
        city: "Clarines",
        name: "MRW CLARINES",
        address: "Av. Fernandez Padilla, Mini C.C. Los Cocos. C.c. Mtc. Local 5 P.b. Clarines.",
        code: "0311000",
      },
      {
        id: "hbKFqChkR5",
        city: "El Tigre",
        name: "MRW EL TIGRE",
        address: "Av. Fco. De Miranda Con Calle 18 Sur. Edif. Los Geranios # 2 Y 3 Frente A La Panaderia Siria.",
        code: "0302000",
      },
      {
        id: "hbKFqChkR6",
        city: "El Tigre",
        name: "MRW EL TIGRE CENTRO",
        address: "Carrera 2 Sur, Entre Calles 2 Y 3, Edificio Hana, Piso 1,. Local Nro 1, Sector Pueblo Nuevo Sur. El Tigre-estado Anzoategui.",
        code: "0313000",
      },
      {
        id: "hbKFqChkR7",
        city: "Lechería",
        name: "MRW LAS GARZAS",
        address: "Av Jorge Rodriguez, Local Mrw 1, Sector Las Garzas Lecheria, Anzoategui.",
        code: "0303000",
      },
      {
        id: "hbKFqChkR8",
        city: "Lechería",
        name: "MRW LECHERIA",
        address: "Av. Ppal. De Lecheria, C.c. La Concha, Nivel Pb, Local 7, Al Lado De La Bodeguilla. Lecheria. Estado Anzoategui.",
        code: "0312000",
      },
      {
        id: "hbKFqChkR9",
        city: "Pariaguán",
        name: "MRW PARIGUAN",
        address: "Calle Bolivar Cruce Con Colombia, Sector Centro Frente Cooperativa De Transporte Pariaguan Express A Pocos Mts De Farmacia Continental.",
        code: "0308000",
      },
      {
        id: "hbKFqChk10",
        city: "Puerto La Cruz",
        name: "MRW PTO LA CRUZ CENTRO",
        address: "Calle Ricauter Edif. D Jorge Piso Pb Local Nro 1 Sector Casco Central Puerto La Cruz Anzoategui.",
        code: "0309000",
      },
      {
        id: "hbKFqChk11",
        city: "Puerto La Cruz",
        name: "MRW PUERTO LA CRUZ",
        address: "Av. Municipal CC Estacion De Servicio Sandoval Nivel Pb Local Nro 137-a, Urbanizacion Pueblo Nuevo, Puerto La Cruz Anzoategui.",
        code: "0304000",
      },
    ]
  },
  {
    name: "Apure",
    agencies: [
      {
        id: "DbXLl5HyH1",
        city: "Achaguas",
        name: "MRW SAN FERNANDO",
        address: "Calle Bolivar Entre Calle Piar Y Girardot, Local Nro S/n Sector Centro, San Fernando De Apure.",
        code: "0400000",
      },
      {
        id: "DbXLl5HyH2",
        city: "Guasdualito",
        name: "MRW GUASGUALITO",
        address: "Calle Cedeño Entre Carrera Arismendi Y General Salon Casa Nro S/n Sector Centro Guasdualito Apure.",
        code: "0401000",
      },
      {
        id: "DbXLl5HyH3",
        city: "San Fernando De Apure",
        name: "MRW SAN FERNANDO CENTRO",
        address: "Av. Caracas A 50 Mts Del Paseo Libertador Multicentro Empresarial Genesis. , Pb Local 1, Sector Centro San Fernando De Apure.",
        code: "0402000",
      },
    ]
  },
  {
    name: "Aragua",
    agencies: [
      {
        id: "rqhYHu7hR1",
        city: "La Victoria",
        name: "MRW LA VICTORIA",
        address: "Av. Victoria Local #2 Pb, Frente Del Estadio Francisco De Miranda, La Victoria Edo. Aragua.",
        code: "0503000",
      },
      {
        id: "rqhYHu7hR2",
        city: "Maracay",
        name: "MRW LA ENCRUCIJADA",
        address: "Av. Principal, C.C. Los Laureles, Nivel P.b, Local 12, Sector La Encrucijada De Turmero. Estado Aragua.",
        code: "0512000",
      },
      {
        id: "rqhYHu7hR3",
        city: "Maracay",
        name: "MRW MARACAY 5 DE JULIO",
        address: "Calle 5 De Julio, Entre Paez Y Miranda. Edif Santimone. P.b.b Local 3, Zona Centro, Diagonal A Imgeve, Maracay Estado Aragua.",
        code: "0504000",
      },
      {
        id: "rqhYHu7hR4",
        city: "Maracay",
        name: "MRW MARACAY BASE ARAGUA",
        address: "Av. Las Delicias C.C. Hotel Paseo Las Delicias Ii Nivel Pb Local 12 Urb Base Aragua Maracay.",
        code: "0513000",
      },
      {
        id: "rqhYHu7hR5",
        city: "Maracay",
        name: "MRW MARACAY LA DEMOCRACIA",
        address: "Av Ayacucho Norte Nro 83, Barrio La Democracia, Maracay Edo Aragua.",
        code: "0510000",
      },
      {
        id: "rqhYHu7hR6",
        city: "Maracay",
        name: "MRW MARACAY LA ROMANA",
        address: "Av. Bolivar Oseste, Numero 165, Edificio Guey 2 Calle Rio Guey, Sector La Romana Maracay.",
        code: "0517000",
      },
      {
        id: "rqhYHu7hR7",
        city: "Maracay",
        name: "MRW MARACAY SANTA ROSA",
        address: "Calle Carabobo, Nro 75-a, Sector Santa Rosa. Maracay, Estado Aragua.",
        code: "0516000",
      },
      {
        id: "rqhYHu7hR8",
        city: "Maracay",
        name: "MRW MARACAY ZONA IND.",
        address: "Av Bermudez Cc Maracay Plaza Nivel Pb Local Pb-82f Urb Centro Maracay Aragua.",
        code: "0501000",
      },
      {
        id: "rqhYHu7hR9",
        city: "San Sebastián",
        name: "MRW S.SEBASTIAN D LOS REYES",
        address: "Calle Bolivar Local Nro 18-2 Sector Centro San Sebastian De Los Reyes Aragua.",
        code: "0509000",
      },
      {
        id: "rqhYHu7h10",
        city: "Turmero",
        name: "MRW TURMERO",
        address: "Calle Marino C/c Calle Penalver C.c Marino Plaza P.b Local 02, Turmero Edo. Aragua.",
        code: "0506000",
      },
      {
        id: "rqhYHu7h11",
        city: "Turmero",
        name: "MRW TURMERO ZONA INDUSTRIAL",
        address: "Av Intercomunal Maracay Turmero C.c. Coche Aragua Local Nro 30 Y 82 Sector La Morita I.",
        code: "0511000",
      },
      {
        id: "rqhYHu7h12",
        city: "Villa De Cura",
        name: "MRW VILLA DE CURA",
        address: "Calle Urdaneta Norte Sector Centro Villa De Cura Aragua Zamora, Estado Aragua.",
        code: "0507000",
      },
    ]
  },
  {
    name: "Barinas",
    agencies: [
      {
        id: "LaFodjozI1",
        city: "Barinas",
        name: "MRW ALTO BARINAS",
        address: "Avenida Francia, Entre Avenidas Pie De Monte Y Tachira, Quinta Dona Ernestina, Nro. 135. Alto Barinas Norte.",
        code: "0605000",
      },
      {
        id: "LaFodjozI2",
        city: "Barinas",
        name: "MRW BARINAS",
        address: "Calle Cedeno C.C. Giamma Nivel Planta Baja Local 6 Sector Centro. Barinas, Estado Barinas.",
        code: "0600000",
      },
      {
        id: "LaFodjozI3",
        city: "Barinas",
        name: "MRW BARINAS 23 DE ENERO",
        address: "Av 23 De Enero Edificio La Fortana Local # 3 A 50mts De La Residencia De La Gobernacion. Barinas Estado Barinas.",
        code: "0606000",
      },
      {
        id: "LaFodjozI4",
        city: "Barinas",
        name: "MRW BARINAS SABANETA",
        address: "Calle 1, Entre Bayon Y Obispo, C.c. Tricolor, Numero 2, Sector 9 De Diciembre De Sabaneta.",
        code: "0604000",
      },
      {
        id: "LaFodjozI5",
        city: "Barinas",
        name: "MRW BARINAS ZONA IND.",
        address: "Av Elias Cordero, Pasos Detras Del Terminal De Pasajeros Edificio Hotel Rey De Reyes, Local 03 Diagonal A Ferreteria El Mecatazo.",
        code: "0602000",
      },
      {
        id: "LaFodjozI6",
        city: "Barinas",
        name: "MRW FORUM",
        address: "Av. 23 De Enero Con Av Guaicaipuro C.c. Forum Local 52, Barinas.",
        code: "0605100",
      },
      {
        id: "LaFodjozI7",
        city: "Barinas",
        name: "MRW STA BARBARA DE BARINAS",
        address: "Calle 12 Entre Carreras 0 Y 00 (Punto De Referencia 2 Cuadras Y Media De Corpoelec) Sector El Progreso, Barinas.",
        code: "0603000",
      },
      {
        id: "LaFodjozI8",
        city: "Socopó",
        name: "MRW SOCOPO",
        address: "Calle 1, Entre Carrera 6 Y 7, Diagonal A La Estrella Oriental ,sector Barrio El Carmen. Socopo-barinas, Zona Postal 5216.",
        code: "0601000",
      },
    ]
  },
  {
    name: "Bolívar",
    agencies: [
      {
        id: "zua12fTjL1",
        city: "Ciudad Bolívar",
        name: "MRW ALTA VISTA",
        address: "Av Puerto Ordaz C.c. Babilonia Mall Nivel Planta Baja Local Pb-30 Sector Alta Vista, Bajando Por El Banco Provincial, Ciudad Guayana Bolivar.",
        code: "0701000",
      },
      {
        id: "zua12fTjL2",
        city: "Ciudad Bolívar",
        name: "MRW BOLIVAR ZONA IND.",
        address: "Av. Nueva Granada. Edif. Gran Sabana. P.b., Local 1 Ciudad Bolivar. Edo. Boliva.",
        code: "0708000",
      },
      {
        id: "zua12fTjL3",
        city: "Ciudad Bolívar",
        name: "MRW CIUDAD BOLIVAR",
        address: "Avenida Republica. Edif. Franco, Pb Locales 1 Y 2, Al Lado De Banesco. Ciudad Bolivar.",
        code: "0700000",
      },
      {
        id: "zua12fTjL4",
        city: "Puerto Ordaz",
        name: "MRW AV LAS AMERICAS",
        address: "Av. Brasil, Urb. Villa Brasil, Manzana 142, Local N2, A 200mts Del Abasto La Espanola, Sector Villa Antillana, Puerto Ordaz.",
        code: "0709000",
      },
      {
        id: "zua12fTjL5",
        city: "Puerto Ordaz",
        name: "MRW PLAZA ATLANTICO",
        address: "Dirección: Centro Comercial Plaza Atlantico Mall, Final Av. Atlantico, Local Pb-12.",
        code: "0711000",
      },
      {
        id: "zua12fTjL6",
        city: "Puerto Ordaz",
        name: "MRW UNARE",
        address: "Calle Neveri, Galpon Mrw, Frente Al Aeropuerto A 500mts De Los Bomberos, Al Lado De Metalmeg. Puerto Ordaz, Edo. Bolivar.",
        code: "0706000",
      },
      {
        id: "zua12fTjL7",
        city: "Santa Elena De Uairen",
        name: "MRW AV LAS AMERICAS",
        address: "Calle Ikabaru, Troncal 10. Casco Central, Local S/n, A 100 Mtrs. Del Hospital Rosario Vera Zurita, Santa Elena De Uairen, Edo. Bolivar.",
        code: "0704000",
      },
    ]
  },
  {
    name: "Carabobo",
    agencies: [
      {
        id: "T3vmzOE9q1",
        city: "Bejuma",
        name: "MRW BEJUMA",
        address: "Av. Carabobo Entre Calle Piar Y Calle Valencia, Local Nro S/n, Sector Union Bejuma, Edo. Carabobo.",
        code: "0809000",
      },
      {
        id: "T3vmzOE9q2",
        city: "Guacara",
        name: "MRW GUACARA",
        address: "Av Carabobo Con Calle Vargas Y Lovera, C.C. Carabobo, Nivel P.b, Local 15, Guacara, Estado Carabobo.",
        code: "0802000",
      },
      {
        id: "T3vmzOE9q3",
        city: "Guigue",
        name: "MRW GUIGUE",
        address: "Av. Miranda Con Av. Michelena, Local 8-54 Sector Guigue, Valencia - Edo Carabobo.",
        code: "0813000",
      },
      {
        id: "T3vmzOE9q4",
        city: "Los Guayos",
        name: "MRW LOS GUAYOS ZONA IND.",
        address: "Carretera Nacional De Los Guayos Con Av. 67 Zona Industiral Municipal Norte. Edif. Tacarigua Local 2 . Valecia- Edo. Caraboro.",
        code: "0802500",
      },
      {
        id: "T3vmzOE9q5",
        city: "Mariara",
        name: "MRW MARIARA",
        address: "Av Bolivar Local Nro 54 Sector Guamacho, A 100 Metros De La Farmacia Coromoto, Barrio El Carmen Mariara Carabobo.",
        code: "0807000",
      },
      {
        id: "T3vmzOE9q6",
        city: "Morón",
        name: "MRW MORON",
        address: "Avda. Yaracuy - Nro 52, Frente Al Banco Banesco, Al Lado Del Banco Bod. Moron Estado Carabobo.",
        code: "0803500",
      },
      {
        id: "T3vmzOE9q7",
        city: "Naguanagua",
        name: "MRW NAGUANAGUA",
        address: "Av. 96-b, C.C. Cristal, Pb. Local B-06 A Dos Locales Del Banco Bicentenario, Por La Entrada Principal. Naguanagua, Edo. Carabobo.",
        code: "0806000",
      },
      {
        id: "T3vmzOE9q8",
        city: "Puerto Cabello",
        name: "MRW PUERTO CABELLO",
        address: "Calle Rondon Edificio El Naranjal Local Nro 2 Frente Al Templo El Refugio, Al Lado De La Clinica San Agustin. Puerto Cabello Edo. Carabobo.",
        code: "0803000",
      },
      {
        id: "T3vmzOE9q9",
        city: "San Joaquín",
        name: "MRW SAN JOAQUIN",
        address: "Av Carabobo C/ Miranda Centro Comercial Eurocenter Planta Baja Local 13 San Joaquin Estado Carabobo.",
        code: "0807100",
      },
      {
        id: "T3vmzOE910",
        city: "Valencia",
        name: "MRW ALIANZA MALL",
        address: "Carretera Nacional Guacara, Urb Ciudad Alianza, C.c. Central Guacara, Local 27, Frente Al Supermercado Central Madeirense. Valencia.",
        code: "0802100",
      },
      {
        id: "T3vmzOE911",
        city: "Valencia",
        name: "MRW AV. LAS FERIAS",
        address: "Av. Bolivar Sur (las Ferias) Con Calle Silva Nro 93-23, Centro Comercial Metro Lara-local C 19, Valencia, Estado Carabobo.",
        code: "0810100",
      },
      {
        id: "T3vmzOE912",
        city: "Valencia",
        name: "MRW FLOR AMARILLO",
        address: "Av. Las Industrias, Cruce Con Av. Principal, Urb. Parque Valencia, C.c. Mega Mercado, Pb , Local 8c1.valencia Edo Carabobo.",
        code: "0804000",
      },
      {
        id: "T3vmzOE913",
        city: "Valencia",
        name: "MRW LA ISABELICA",
        address: "Av. 04 Sector 10, Vereda 14, Local 01, Urb. La Isabelica. Valencia - Carabobo.",
        code: "0812000",
      },
      {
        id: "T3vmzOE914",
        city: "Valencia",
        name: "MRW MORRO II",
        address: "Av. 73 Via De Servicio Casa Nro. 656 Local 656-b, Al Lado De Mc Donalds A 50 Metros Del C.c. Fin De Siglo San Diego.",
        code: "0815100",
      },
      {
        id: "T3vmzOE915",
        city: "Valencia",
        name: "MRW PARAPARAL",
        address: "Urbanizacion Paraparal Avenida Principal Centro Comercial Los Cristales Local Nro 02 , Al Lado De La Pasteleria Capuchinno. Los Guayos, Estado Carabobo.",
        code: "0826000",
      },
      {
        id: "T3vmzOE916",
        city: "Valencia",
        name: "MRW SAN DIEGO TERRAZAS DE CASTILLITO",
        address: "Av. Don Julio Centeno, Calle 103, Centro Comercial Prati, Nivel Pb, Local L-4, Urb. Terrazas El Castillito, Frente A Mar De La Ceramica, San Diego, Edo. Carabobo.av. Don Julio Centeno, Calle 103, Cent.",
        code: "0818000",
      },
      {
        id: "T3vmzOE917",
        city: "Valencia",
        name: "MRW VALENCIA AV. LARA",
        address: "Av. Lara Con Calle Uslar, Local 87-107. Frente A Molinari Caccia Guerra, Valencia Carabobo.",
        code: "0823000",
      },
      {
        id: "T3vmzOE918",
        city: "Valencia",
        name: "MRW VALENCIA BIG LOW",
        address: "Calle 97, C.C. Ciudad Valencia, Pb, Local B4. Urb. Zona Industrial Castillito. Valencia, Estado Carabobo.",
        code: "0801000",
      },
      {
        id: "T3vmzOE919",
        city: "Valencia",
        name: "MRW VALENCIA CENTRO",
        address: "Av. Miranda Local 118-31 Mrw Detras De Imgeve Av. Bolivar Norte Frente A La Kia Sector San Jose Valencia-carabobo.",
        code: "0800000",
      },
      {
        id: "T3vmzOE920",
        city: "Valencia",
        name: "MRW VALENCIA EL PARRAL",
        address: "Las 4 Avenidas, C.C. Profesional Ceravica Pb, Local 2, Urb. El Parral - Edo. Carabobo.",
        code: "0814000",
      },
      {
        id: "T3vmzOE921",
        city: "Valencia",
        name: "MRW VALENCIA GOBERNACION",
        address: "Calle Paez Entre Montes De Oca Y Carabobo C.c. Papin Pb Local Nro 1, Centro De Valencia ( Cerca Del Capitolio). Edo Carabobo.",
        code: "0820000",
      },
      {
        id: "T3vmzOE922",
        city: "Valencia",
        name: "MRW VALENCIA LA CANDELARIA",
        address: "Av. Aranzazu, Edificio Vorma, Piso P.b., Local Pb-3, La Candelaria. Valencia Edo. Carabobo.",
        code: "0810000",
      },
      {
        id: "T3vmzOE923",
        city: "Valencia",
        name: "MRW VALENCIA NORTE",
        address: "Av. Bolivar Norte, Sector Majay, Local Nro 151-54, , Frente A La Torre Princiapal (banco Bnc). Valencia, Edo. Carabobo.",
        code: "0816000",
      },
      {
        id: "T3vmzOE924",
        city: "Valencia",
        name: "MRW VALENCIA SAN DIEGO",
        address: "Av. Don Julio Centeno C.c. Metro Plaza P.b Local 33 San Diego Edo. Carabobo.",
        code: "0815000",
      },
      {
        id: "T3vmzOE925",
        city: "Valencia",
        name: "MRW VALENCIA SUR",
        address: "Autopista Valencia - Campo Carabobo. Centro Comercial El Prado, Planta Baja Local B 6. Los Caobos, Valencia-edo.carabobo.",
        code: "0808000",
      },
      {
        id: "T3vmzOE926",
        city: "Valencia",
        name: "MRW VALENCIA TRIGAL",
        address: "Av. Principal De Manongo, C.c. Patio Trigal. Nivel Pb Local 208 A Urb Trigal Norte, Valencia Carabobo Zona Postal 2001.",
        code: "0805000",
      },
      {
        id: "T3vmzOE927",
        city: "Valencia",
        name: "MRW VALENCIA ZONA IND.",
        address: "Av.prolongacion Michelena C.C. Mycra Local 10 Zona Industrial Valencia.",
        code: "0811000",
      },

    ]
  },
  {
    name: "Cojedes",
    agencies: [
      {
        id: "nzGcREp2u1",
        city: "San Carlos",
        name: "MRW SAN CARLOS",
        address: "Calle Sucre Entre Zamora Y Libertad Local #8-33, Edo. Cojedes.",
        code: "0900000",
      },
      {
        id: "nzGcREp2u2",
        city: "Tinaquillo",
        name: "MRW TINAQUILLO",
        address: "Av. Madariaga, Entre Calle Cedeno Y Calle Negro Primero, Tinaquillo - Estado Cojedes.",
        code: "0901000",
      },
    ]
  },
  {
    name: "Delta Amacuro",
    agencies: [
      {
        id: "faenTiX0w1",
        city: "Tucupita",
        name: "MRW TUCUPITA",
        address: "Calle Dalla Costa # 22, Local 1, Edf. Ciarcia Frente A La Plaza Bolivar, Pq. San Jose, Mncp: Tucupita, Cd: Tucupita Edo: Delta Amacuro.",
        code: "1000000",
      },
    ]
  },
  {
    name: "Distrito Capital",
    agencies: [
      {
        id: "9bZ9t3fCi1",
        city: "Caracas",
        name: "MRW ALTAMIRA",
        address: "Av San Juan Bosco De Altamira Con 1era Transversal , Res, Excelsior Pb Local 2 Altamira - Miranda.",
        code: "	0115000",
      },
      {
        id: "9bZ9t3fCi2",
        city: "Caracas",
        name: "MRW ANDRES BELLO",
        address: "Av Andres Bello Colegio Nacional De Periodista Local 4 Pb Frente A Pollos Riviera.",
        code: "0143000",
      },
      {
        id: "9bZ9t3fCi3",
        city: "Caracas",
        name: "MRW ANTIMANO/ LA YAGUARA",
        address: "Calle Real Boulevard De Antimano, Entre La Jefatura Civil Y La Plaza Bolivar De Antimano, Local Mrw.",
        code: "0146000",
      },
      {
        id: "9bZ9t3fCi4",
        city: "Caracas",
        name: "MRW AV. CASANOVA",
        address: "Inicio Av. Casanova Entre Calle San Antonio Y Calle El Colegio, C.c. Del Este, Nro 21. Diagonal Al Hotel Kurssal, A Media Cuadra Del Arabito De Sabana Grande.",
        code: "0141000",
      },
      {
        id: "9bZ9t3fCi5",
        city: "Caracas",
        name: "MRW BARUTA",
        address: "Calle Negro Primero C/c Sucre N 15-04 Al Lado De Eurosweaters-baruta.",
        code: "0117000",
      },
      {
        id: "9bZ9t3fCi6",
        city: "Caracas",
        name: "MRW BELLO MONTE",
        address: "Avenida Miguelangel, Edificio Oberon, Local E, Frente A La Pasteleria La Sabrina, Al Lado De Pinta Casa, Colinas De Bello Monte. Codigo Postal 1060.",
        code: "0102000",
      },
      {
        id: "9bZ9t3fCi7",
        city: "Caracas",
        name: "MRW CAMPO CLARO",
        address: "Av. Francisco De Miranda Con Calle Guanche. Edif. Valencia I P.b. Al Lado Del Banco Bod. Campo Claro Los Dos Caminos.",
        code: "0109000",
      },
      {
        id: "9bZ9t3fCi8",
        city: "Caracas",
        name: "MRW CAPITOLIO",
        address: "Avenida Baralt Esquina De Conde A Pinango , Casona Nro 11, Parroquia Altagracia, Al Lado De La Jefatura Catedral.",
        code: "0145000",
      },
      {
        id: "9bZ9t3fCi9",
        city: "Caracas",
        name: "MRW CARICUAO",
        address: "Redoma De Ruiz Pineda, Centro Comercial Caricuao Plaza, Piso 2, Local 127, Parroquia Caricuao, Municipio Libertador, Caracas Distrito Capital.",
        code: "0132000",
      },
      {
        id: "9bZ9t3fCi10",
        city: "Caracas",
        name: "MRW CATIA",
        address: "Av. Sucre, C.C. Oeste Nivel 3 Local 038 Sector Catia, Caracas.",
        code: "0128000",
      },
      {
        id: "9bZ9t3fCi12",
        city: "Caracas",
        name: "MRW CENTRO",
        address: "Av. Universidad, Esq. De Sociedad A Gradillas, Edif. Humbolt P.b. Local 4 Mrw",
        code: "0104000",
      },
      {
        id: "9bZ9t3fCi13",
        city: "Caracas",
        name: "MRW CHACAITO",
        address: "Av. Pichincha Entre Salida Del Metro Y Av. Tamanaco Cc Unico Nivel Pb Local 5 Y 6 Urb El Rosal.",
        code: "0148000",
      },
      {
        id: "9bZ9t3fCi14",
        city: "Caracas",
        name: "MRW CHACAO EL MUÑECO",
        address: "Calle El Muñeco Entre Av. Fco. De Miranda Y Av. Libertador Edif. Guan, Pb, Local 7. Chacao.",
        code: "0105000",
      },
      {
        id: "9bZ9t3fCi15",
        city: "Caracas",
        name: "MRW CHUAO",
        address: "Av Ernesto Blon Cc Ciudad Tamanaco Nivel Pb Local F Sector Chuao Caracas (chacao) Miranda.",
        code: "0106000",
      },
      {
        id: "9bZ9t3fCi16",
        city: "Caracas",
        name: "MRW EL BOSQUE",
        address: "Calle El Carmen Entre Av. El Empalme Y Ppal. Del Bosque Qta.torre La Vega.pb Local 5.(media Cuadra Fedecamaras).",
        code: "0131000",
      },
      {
        id: "9bZ9t3fCi17",
        city: "Caracas",
        name: "MRW EL CEMENTERIO",
        address: "Av Los Totumos Entre Av Louis Braillet Y Floresta, Casa 20 Local Unico, Prado De Maria El Cementerio.",
        code: "0126000",
      },
      {
        id: "9bZ9t3fCi18",
        city: "Caracas",
        name: "MRW EL HATILLO",
        address: "Calle Matadero, Centro Comercial Priscos, Nivel Pb Of 904-4 Urb El Hatillo Caracas.",
        code: "0125000",
      },
      {
        id: "9bZ9t3fCi19",
        city: "Caracas",
        name: "MRW EL LLANITO",
        address: "Av. Pcpal Del Llanito En La Ferreteria Casatrigo Punto De Referencia Al Frente Del Supermercado Don Sancho El Llanito",
        code: "0103000",
      },
      {
        id: "9bZ9t3fCi20",
        city: "Caracas",
        name: "MRW EL PARAISO",
        address: "Entre Av. Las Fuentes Y Av. Washinton, Calle 1, Quinta Francelis, Pb, Local 1, Urbanizacion El Paraiso, Municipio Libertador, Caracas.",
        code: "0107000",
      },
      {
        id: "9bZ9t3fCi21",
        city: "Caracas",
        name: "MRW EL VALLE",
        address: "Av. Intercomunal Del Valle, Cc El Palmar, Residencias Don Pedro, Torre F, Local Mrw Pb,el Valle.",
        code: "0142000",
      },
      {
        id: "9bZ9t3fCi22",
        city: "Caracas",
        name: "MRW FUERTE TIUNA",
        address: "Av. Las Escuelas, Centro Simon Bolivar Frente Al Stadium Jose Antonio Casanova. Fuerte Tiuna.",
        code: "0151000",
      },
      {
        id: "9bZ9t3fCi23",
        city: "Caracas",
        name: "MRW LA CANDELARIA",
        address: "Perico A Puente Yanez Edf. Serrano Pb. Local 3 La Candelaria.",
        code: "0140000",
      },
      {
        id: "9bZ9t3fCi24",
        city: "Caracas",
        name: "MRW LA CASTELLANA",
        address: "Calle Urdaneta Con Principal De La Castellana, Quinta Aurana, P.b. A Media Cuadra Del Restaurant La Estancia. La Castellana.",
        code: "0147000",
      },
      {
        id: "9bZ9t3fCi25",
        city: "Caracas",
        name: "MRW LA FLORIDA",
        address: "Urb. La Florida. Av. Los Chaguaramos.qta Coroli. Caracas.",
        code: "0133000",
      },
      {
        id: "9bZ9t3fCi26",
        city: "Caracas",
        name: "MRW LA PIRAMIDE",
        address: "Av Rio Caura Centro Empresarial La Piramide Pb Local 32c Prado Del Este.",
        code: "0118000",
      },
      {
        id: "9bZ9t3fCi27",
        city: "Caracas",
        name: "MRW LA TRINIDAD",
        address: "Calle Del Arenal, Qta. Laura, Urbanizacion La Trinidad, Municipio Baruta, A Dos Cuadras Del Farmatodo De La Zona Ind. La Trinidad, Frente A La Clinica Veterinaria Avila.",
        code: "0110000",
      },
      {
        id: "9bZ9t3fCi28",
        city: "Caracas",
        name: "MRW LA URBINA",
        address: "Av. Ppal. La Urbina. Edif. Apulia. P.b. Local 4, Cerca A La Panaderia Tulipan. La Urbina. Edo. Miranda.",
        code: "0120000",
      },
      {
        id: "9bZ9t3fCi29",
        city: "Caracas",
        name: "MRW LAS ACACIAS",
        address: "Avenida General Medina Angarita, Edificio Residencias Betania Planta Baja Local Mrw, Urbanizacion Las Acacias. ( Pto De Referencia Frente A Repuestos Pamaca).",
        code: "0119000",
      },
      {
        id: "9bZ9t3fCi30",
        city: "Caracas",
        name: "MRW LAS MERCEDES",
        address: "Av. Veracruz. Edif. Matisco. P.b. Diagonal A Conatel, Urb. Las Mercedes, Caracas Miranda.",
        code: "0123000",
      },
      {
        id: "9bZ9t3fCi31",
        city: "Caracas",
        name: "MRW LAS MINAS",
        address: "Av. Ppal.las Minas De Baruta, C.c. Luna, Local #15, Frente A La Parada Delas Camionetas Al Silencio, A 50 Mts De La Policia Fatima, Las Minas De Baruta.",
        code: "0138000",
      },
      {
        id: "9bZ9t3fCi32",
        city: "Caracas",
        name: "MRW LEBRUN PETARE",
        address: "Calle Los Naranjos Edif Lebrun Piso Pb Local 19, Frente Al Liceo Mariano Picon Salas . Urb Lebrun Caracas Petare Miranda.",
        code: "0113000",
      },
      {
        id: "9bZ9t3fCi33",
        city: "Caracas",
        name: "MRW LECUNA",
        address: "Calle Sur 3, Esquina De Zamuro A Miseria, Edif. Inducentro Local 1 Pb, A 20 Mts De La Av. Lecuna. Santa Rosalia.",
        code: "0135000",
      },
      {
        id: "9bZ9t3fCi34",
        city: "Caracas",
        name: "MRW LOS CAOBOS",
        address: "Av. Panama Con Av. Libertador, Qta. Mrw Los Caobos, Detras De Restaurant Gran Yein, Subiendo Por La Torre Polar. Urb Los Caobos Caracas. Codigo Postal 1050.",
        code: "0101000",
      },
      {
        id: "9bZ9t3fCi35",
        city: "Caracas",
        name: "MRW LOS CHAGUARAMOS",
        address: "Av. El Parque, C.c. Los Chaguaramos, Nivel P.b, Local 10, Urb. Las Chaguaramos, Caracas.",
        code: "0111000",
      },
      {
        id: "9bZ9t3fCi36",
        city: "Caracas",
        name: "MRW LOS CHORROS",
        address: "Av. Pincipal La Carlota Entre Av. Francisco De Miranda Y Romulo Gallegos, Edf. Bertha, Local 05 Punto De Referencia Frente A La Zona De Carga Del Millenium.",
        code: "0116000",
      },
      {
        id: "9bZ9t3fCi37",
        city: "Caracas",
        name: "MRW LOS PALOS GRANDES",
        address: "Av Andres Bello De Los Palos Grandes Con 2da Transversal Edificio Vista Hermosa Pb Local C, Urbanizacion Los Palos Grandes, Caracas.",
        code: "0150000",
      },
      {
        id: "9bZ9t3fCi38",
        city: "Caracas",
        name: "MRW LOS ROSALES",
        address: "Av. Los Laureles Con Av. Roosevelt, Res. Tiuna Local E. Pb Frente A Plaza Tiuna Los Rosales.",
        code: "0122000",
      },
      {
        id: "9bZ9t3fCi39",
        city: "Caracas",
        name: "MRW PALO VERDE",
        address: "Centro Comercial Palo Verde , Nivel 2, Local 11-2. Frente De Farmacia Naturista, Dentro De Centro De Comunicaciones Movilnet Cantv.",
        code: "0113200",
      },
      {
        id: "9bZ9t3fCi40",
        city: "Caracas",
        name: "MRW PANTIN",
        address: "Calle Pantin, Entre Calle Saman Y Los Angeles, Galpon Mrw. Al Frente De La Policia De Chacao.urbanizacion Estado Leal. Chacao.",
        code: "0137000",
      },
      {
        id: "9bZ9t3fCi41",
        city: "Caracas",
        name: "MRW PLAZA ESTRELLA",
        address: "Plaza Estrella A San Felipe, Res. Dorabel, Pb Local 3. A Media Cuadra Del Pasaje Anauco. San Bernardino.",
        code: "0108000",
      },
      {
        id: "9bZ9t3fCi42",
        city: "Caracas",
        name: "MRW PLAZA LAS AMERICAS",
        address: "Centro Comercial Plaza Las Americas, Nivel Oro, Local 107-a, El Cafetal.",
        code: "0103100",
      },
      {
        id: "9bZ9t3fCi43",
        city: "Caracas",
        name: "MRW QUINTA CRESPO",
        address: "Esquina Barcenas A Dolores, Edificio E2 Piso 1 Oficina 1, Urbanizacion Quinta Crespo. Punto De Referencia Detras De Rctv. Caracas.",
        code: "0139000",
      },
      {
        id: "9bZ9t3fCi44",
        city: "Caracas",
        name: "MRW SABANA GRANDE",
        address: "Av Orinoco Entre 2da Calle Y Caroni Qta Ismenia Local Pb - Cp 1050 - Sector Sabana Grande, Bello Monte Norte",
        code: "0114000",
      },
      {
        id: "9bZ9t3fCi45",
        city: "Caracas",
        name: "MRW SAN MARTIN",
        address: "Av. San Martin Cruce Con Av. Santander, C.C. Maracaibo, Nivel Mezanina, Local 12, Sector San Martin-caracas.",
        code: "0134000",
      },
      {
        id: "9bZ9t3fCi46",
        city: "Caracas",
        name: "MRW SANTA MONICA",
        address: "Av. Arturo Michelena C/c Agusin Codazzi, Qta. Ceiba, Al Lado De La Farmacia Bama, Santa Monica, Caracas.",
        code: "0130000",
      },
      {
        id: "9bZ9t3fCi47",
        city: "Caracas",
        name: "MRW SANTA SOFIA",
        address: "Av. Ppal. Santa Sofia. C.c. Sta. Sofia. Local Z-3. P.b. Santa Sofia.",
        code: "0124000",
      },
      {
        id: "9bZ9t3fCi48",
        city: "Caracas",
        name: "MRW SEBUCAN",
        address: "Avenida Romulo Gallegos Entre Avenida Principal De Sebucan Y Avenida Sucre De Los Dos Caminos, Residencias Carlo Local 2. Los Dos Caminos.",
        code: "0144000",
      },
      {
        id: "9bZ9t3fCi49",
        city: "Caracas",
        name: "MRW EL JUNQUITO",
        address: "C.C. Casa Junko Pb, Local A7. Kilometro 18 Del Junquito, Antigua Bomba.",
        code: "0129000",
      },
      {
        id: "9bZ9t3fCi50",
        city: "Caracas",
        name: "MRW MONTALBAN",
        address: "Mortalban Ii, 2da Transversal Centro Comercial La Villa",
        code: "0132100",
      },

    ]
  },
  {
    name: "Falcón",
    agencies: [
      {
        id: "ZaDEXvVlo1",
        city: "Coro",
        name: "MRW CORO",
        address: "Calle Zamora. Esquina Callejon Las Flores E Iturbe Local S/n Sector Chimpire Coro Mcipio Miranda Edo Falcon Santa Ana De Coro. Codigo Postal 4101.",
        code: "1100000",
      },
      {
        id: "ZaDEXvVlo2",
        city: "Coro",
        name: "MRW EL CASTILLO",
        address: "Avenida Manaure, Esquina Con Calle Monzon . C.c. El Castillo Don Leoncio, Pb, Local Nro 10. Coro. Codigo Postal 4101.",
        code: "1105000",
      },
      {
        id: "ZaDEXvVlo3",
        city: "Dabajuro",
        name: "MRW PUERTA MARAVEN",
        address: "Calle San Roman Entre Av. General Pelayo Y Av. Ollarvides, Diagonal A Rias Altas.",
        code: "1104000",
      },
      {
        id: "ZaDEXvVlo4",
        city: "Judibana",
        name: "MRW CAJA AGUA",
        address: "Calle Manuelita Saenz, Entre Calle Comercio Y Providencia, Local 1, Sector De Caja De Agua, Diagonal A La Iglesia Mormones",
        code: "1103000",
      },
      {
        id: "ZaDEXvVlo5",
        city: "Punto Fijo",
        name: "MRW PUNTO FIJO AV. MONAGAS",
        address: "Calle Monagas Entre Garces Y Zamora Edif. Lucriscar Planta Baja, Punto Fijo Edo. Falcon.",
        code: "1106000",
      },
      {
        id: "ZaDEXvVlo6",
        city: "Tucacas",
        name: "MRW TUCACAS",
        address: "Av Libertador De Tucacas, Diagonal Al Hotel La Suerte , Local Nro #1. Edo. Falcon. Codigo Postal 2054.",
        code: "1102000",
      },
    ]
  },
  {
    name: "Guárico",
    agencies: [
      {
        id: "X9NtasYYD1",
        city: "Altagracia De Orituco",
        name: "MRW ALTAGRACIA DE ORITUCO",
        address: "Calle Hurtado Ascanio Cruce Con Vuelvan Cara. Edf. Residencias La Paz, Pb, Local 2, Sector Las Brisas Del Este Altagracia De Orituco. Edo. Guarico. Codigo Postal 2320.",
        code: "1205000",
      },
      {
        id: "X9NtasYYD2",
        city: "Calabozo",
        name: "MRW CALABOZO",
        address: "Carrera 12 Entre Calle 4 Y 5 C.c Coromoto Frente A La Plaza Bolivar . Calabozo. Codigo Postal 2312.",
        code: "1201000",
      },
      {
        id: "X9NtasYYD3",
        city: "San Juan De Los Morros",
        name: "MRW S. JUAN DE LOS MORROS",
        address: "Calle El Carmen, Edf. Rauseo, Local 2 Bajando Por La Gobernacion, Diagonal A La Cantv, Zona Postal 2301.",
        code: "1200000",
      },
      {
        id: "X9NtasYYD4",
        city: "Tucupido",
        name: "MRW TUCUPIDO",
        address: "Calle Salom Nro 24 Diagonal A La Alcaldia, Entre San Pablo Y Zaraza, Local Mrw Pb.",
        code: "1204000",
      },
      {
        id: "X9NtasYYD5",
        city: "Valle De La Pascua",
        name: "MRW VALLE DE LA PASCUA",
        address: "Calle Gonzalez Padron, Centro Comercial Star Center, Local B-10, Valle De La Pascua, Estado Guarido.",
        code: "1202000",
      },
      {
        id: "X9NtasYYD6",
        city: "Zaraza",
        name: "MRW ZARAZA",
        address: "Calle Bolivar, Entre Ayacucho Y Sucre , Local Mrw, Pb, A 100 Mts Del Saime, Sector Centro, Zaraza, Estado Guarico. Codigo Postal 2332.",
        code: "1203000",
      },
    ]
  },
  {
    name: "La Guaira",
    agencies: [
      {
        id: "gzZhPxd4qz1",
        city: "Catia La Mar",
        name: "MRW CATIA LA MAR",
        address: "Calle 13 Atlantida CC Pemysa Frente A Oficina De Corpoelec, Catia La Mar Frente A Corpoelec. Codigo Postal 1162.",
        code: "2201000",
      },
    ]
  },
  {
    name: "Lara",
    agencies: [
      {
        id: "N179YyGBD1",
        city: "Barquisimeto",
        name: "MRW ANDRES BELLO",
        address: "Carrera 22 Con Cale 22 Andres Bello Local Nro 4 Barquisimeto.",
        code: "1300300",
      },
      {
        id: "N179YyGBD2",
        city: "Barquisimeto",
        name: "MRW AV. MORAN",
        address: "Carrera 21, Entre Av. Moran Y Calle 8, C.c. Plaza Sevilla Local 28 Y 29. Barquisimeto.",
        code: "1303100",
      },
      {
        id: "N179YyGBD3",
        city: "Barquisimeto",
        name: "MRW AV. VENEZUELA",
        address: "Av Venezuela Con Calle 21, Edificio Lazio, Local Nro. 02, Bqto. Edo. Lara. Codigo Postal 3001.",
        code: "1310000",
      },
      {
        id: "N179YyGBD4",
        city: "Barquisimeto",
        name: "MRW BABILOM",
        address: "Calle 19 Con Av Libertador Zona Industrial I C.c Libertador Local 13-b.",
        code: "1308000",
      },
      {
        id: "N179YyGBD5",
        city: "Barquisimeto",
        name: "MRW BARQUISIMETO NUEVA SEGOVIA",
        address: "Calle 3 Entre Carrera 1 Y Av Lara, Casa Nro Al-99 Urb Nueva Segovia Barquisimeto Edo Lara. Codigo Postal 3001.",
        code: "1307000",
      },
      {
        id: "N179YyGBD6",
        city: "Barquisimeto",
        name: "MRW BQMETO ESTE",
        address: "Calle 15, Entre Carreras 20 Y 21, Local No. 5, Diagonal A La Clinica San Francisco. Barquisimeto,estado Lara.",
        code: "1303000",
      },
      {
        id: "N179YyGBD7",
        city: "Barquisimeto",
        name: "MRW BQMETO OESTE",
        address: "Av. Florencio Jimenez, C.c. Arcoiris, Local 5, P.b., Frente Al Decanato De La Ucla, Barquisimeto, Edo. Lara. Codigo Postal 3001.",
        code: "1301000",
      },
      {
        id: "N179YyGBD8",
        city: "Barquisimeto",
        name: "MRW BQTO CENTRO",
        address: "Av. Venezuela Entre Calles 39 Y 40, Numero 39-55, Sentido Oeste-este. Codigo Postal 3001. Barquisimeto.",
        code: "1300000",
      },
      {
        id: "N179YyGBD9",
        city: "Barquisimeto",
        name: "MRW CANAIMA",
        address: "Calle 55 Entre Av. Pedro Leon Torres Y Carrera 19, C.c. Canaima, Local F-02. Zona Este Barquisimeto. Codigo Postal 3001.",
        code: "1300200",
      },
      {
        id: "N179YyGBD10",
        city: "Barquisimeto",
        name: "MRW EL RECREO",
        address: "Av. Libertador. C.c. El Rosario. Local 5. Frente Al Ipasme. Codigo Postal 3001.",
        code: "1308100",
      },
      {
        id: "N179YyGBD11",
        city: "Barquisimeto",
        name: "MRW PATARATA",
        address: "Av. Libertador Entre Av. Argemiro Bracamonte Y Av. Lopez Contrera, Sector Patarata, Centro Recreacional Parque Jardin, Local 04, Barquisimeto Edo. Lara. Codigo Postal 3001.",
        code: "1307100",
      },
      {
        id: "N179YyGBD12",
        city: "Cabudare",
        name: "MRW CABUDARE",
        address: "Av. Santa Barbara, Entre Calles Guillermo Alvizu Y La Cruz, C.C. Sta. Barbara, Local 2, Detras Ferreteria Tabure. Codigo Postal 3023.",
        code: "1304000",
      },
      {
        id: "N179YyGBD13",
        city: "Cabudare",
        name: "MRW CABUDARE SUR",
        address: "Av. El Placer Cc El Trigalpa Planta Baja Local 5 Cabudare",
        code: "1309000",
      },
      {
        id: "N179YyGBD14",
        city: "Carora",
        name: "MRW CARORA",
        address: "Av. Fco De Miranda / Clls 15a Y 16 Casa Nro 15 Sector Egidio Montesino-carora A 50 Mts De La Plaza Chio Zubillaga. Codigo Postal 3050.",
        code: "1302000",
      },
      {
        id: "N179YyGBD15",
        city: "Duaca",
        name: "MRW VALLE LINDO",
        address: "Autopista Via Duaca Km 10 Sector Sabana Grande Al Lado De La Farmacia San Ignacio, Zona Norte, Bqto. Codigo Postal 3001.",
        code: "1306000",
      },
      {
        id: "N179YyGBD16",
        city: "Quíbor",
        name: "MRW QUIBOR",
        address: "Calle 8 Entre Avenida 8 Y 9 A 200mts. Del Supermercado La Plama.",
        code: "1305000",
      },
    ]
  },
  {
    name: "Miranda",
    agencies: [
      {
        id: "tYROWZMjG1",
        city: "Charallave",
        name: "MRW CHARALLAVE",
        address: "Calle 9, Avenida Jose Gregorio Hernandez Con Avenida Bolivar Edf. Los Samanes Nro 03 Sector Casco Central Charallave Miranda.",
        code: "1501000",
      },
      {
        id: "tYROWZMjG2",
        city: "Cúa",
        name: "MRW CUA",
        address: "Urbanizacion Jardines De Santa Rosa, C.C. El Colonial, Local 26-a, Cua, Miranda.",
        code: "1509000",
      },
      {
        id: "tYROWZMjG3",
        city: "Guarenas",
        name: "MRW GUARENAS",
        address: "Calle 19 De Abril Entre Calle Comercio Y Andres Bello, Local 1, A Media Cuadra De La Plaza La Candelaria Guarenas Edo Miranda.",
        code: "1503000",
      },
      {
        id: "tYROWZMjG4",
        city: "Guatire",
        name: "MRW GUATIRE",
        address: "Guatire, Calle Zamora Numero 47, Local Pb-1, Edificio Quinta Arelis.",
        code: "1504000",
      },
      {
        id: "tYROWZMjG5",
        city: "Guatire",
        name: "MRW GUATIRE OASIS",
        address: "Av. Intercomunal Guarenas - Guatire En El Centro Comercial Oasis Center, Pb, Local 15, Frente Al Banco Bicentenario.",
        code: "1510000",
      },
      {
        id: "tYROWZMjG6",
        city: "Higuerote",
        name: "MRW HIGUEROTE",
        address: "Calle El Rio, Cc Marti Plaza, Local 1, Higuerote Edo. Miranda.",
        code: "1506000",
      },
      {
        id: "tYROWZMjG7",
        city: "Ocumare Del Tuy",
        name: "MRW OCUMARE DEL TUY",
        address: "Avenida Miranda Con Calle Toribio Mota, Edif. Televisa, Pb. Frente A La Parada De Parosca.",
        code: "1501500",
      },
      {
        id: "tYROWZMjG8",
        city: "Río Chico",
        name: "MRW RIO CHICO",
        address: "Calle Comercio, Local Mrw. Al Lado De La Farmacia Las Mercedes, Rio Chico- Municipio Paez- Edo. Miranda.",
        code: "1507000",
      },
      {
        id: "tYROWZMjG9",
        city: "San Antonio De Los Altos",
        name: "MRW SAN ANTONIO DE LOS ALTOS",
        address: "Carreta Panamericana, Kilometro 16, C.c. La Casona Ii, Piso 1, Local #2-17 Al Lado De Cinex.",
        code: "1505000",
      },
      {
        id: "tYROWZMjG10",
        city: "Santa Teresa",
        name: "MRW STA TERESA DEL TUY",
        address: "Calle Ayacucho Edif Don Guillermo Piso 1 Of 4 Zona Centro Santa Teresa Del Tuy Miranda.",
        code: "1508000",
      },
    ]
  },
  {
    name: "Monagas",
    agencies: [
      {
        id: "P078ZAOEP1",
        city: "Maturín",
        name: "MRW MATURIN AV. RAUL LEONI",
        address: "Av. Raul Leoni Entre Carrera 3 (antigua Av. Rivas) Y Carrera 4 (antigua Prolongacion) Frente Al Polideportivo, Maturin Edo. Monagas.",
        code: "1608000",
      },
      {
        id: "P078ZAOEP2",
        city: "Maturín",
        name: "MRW MATURIN CENTRO",
        address: "Calle 14(antigua Av.rojas) C/c C.10 (antigua Barreto), Edif Bravo Piso P.b Local 01, Diagonal A La Cantv, Sector Centro Maturin Monagas.",
        code: "1603000",
      },
      {
        id: "P078ZAOEP3",
        city: "Maturín",
        name: "MRW MATURIN LA FLORESTA",
        address: "Cr 1nro 4 C.c. La Redoma Nivel Pb Local 5 Sector Brisas Del Aeropuerto, Diagonal Al Seniat, Maturin Monagas.",
        code: "1609000",
      },
      {
        id: "P078ZAOEP4",
        city: "Maturín",
        name: "MRW MATURIN NORTE",
        address: "Av. Principal Via Viboral, Centro Comercial Virgen Del Valle, Local 28-a Pb Sector Tipuro, Parroquia Boqueron, Municipio Maturin Del Estado Monagas.",
        code: "1606000",
      },
      {
        id: "P078ZAOEP5",
        city: "Maturín",
        name: "MRW MATURIN PLAZA EL INDIO",
        address: "Av. Bicentenario Edif. Zamora, P.b. Al Lado De La Linea De Taxi Lo Mejor De Lo Mejor.",
        code: "1610000",
      },
      {
        id: "P078ZAOEP6",
        city: "Maturín",
        name: "MRW MATURIN ZONA INDUSTRIAL",
        address: "Calle Principal De La Cruz De La Paloma C/c La Macarenas Pb Local 5.",
        code: "	1607000",
      },
      {
        id: "P078ZAOEP7",
        city: "	Punta De Mata",
        name: "MRW PUNTA DE MATA",
        address: "Calle 5 De Julio C/c Nueva Local Mrw Detras Del Banco Caroni",
        code: "1602000",
      },
      {
        id: "P078ZAOEP8",
        city: "Temblador",
        name: "MRW TEMBLADOR",
        address: "Calle Bolivar. No 70-a. Sector La Plaza Al Lado De La Carniceria El Brahmon. Monagas.",
        code: "1605000",
      },
    ]
  },
  {
    name: "Mérida",
    agencies: [
      {
        id: "5iNtfPslZ1",
        city: "Ejido",
        name: "MRW EJIDO",
        address: "Av. Fernandez Pena Casa Planta Baja Nro 133-c Sector Montalban, A 100 Mts Del Diario Frontera. Centro Ejido Merida.",
        code: "1404000",
      },
      {
        id: "5iNtfPslZ2",
        city: "El Vigía",
        name: "MRW EL VIGIA",
        address: "Calle 3 Con Av. Don Pepe Rojas, Local Galpon Nro. S/n Barrio Bolivar El Vigia Edo, Merida.",
        code: "1402000",
      },
      {
        id: "5iNtfPslZ5",
        city: "Mérida",
        name: "MRW MDA LOS PROCERES",
        address: "Av Los Proceres, Calle La Orquidea , Minicentro Comercial , Don Luis, Local 2b O Mrw.",
        code: "1406000",
      },
      {
        id: "5iNtfPslZ6",
        city: "Mérida",
        name: "MRW MERIDA CUBO ROJO",
        address: "Av Gonzalo Picon Con Viaducto Miranda, Cc Cubo Rojo Nivel Pb Local 2,4,6,7,8 Sector Glorias Patrias Merida.",
        code: "1400000",
      },
      {
        id: "5iNtfPslZ7",
        city: "Mérida",
        name: "MRW MERIDA MILLA",
        address: "Av 5 Con Esquina Calle 16 Local Nro 14-106, Sector Belen Municipio Libertador Merida.",
        code: "1405000",
      },
      {
        id: "5iNtfPslZ8",
        city: "Mérida",
        name: "MRW MERIDA PASEO DE LA FERIA",
        address: "Av. Don Tulio Febres Cordero, Con Calle 29, Detras Del Edf. Administrativo De La Ula, Edf. El Paseo Pb, Local Unico.",
        code: "1401000",
      },
      {
        id: "5iNtfPslZ3",
        city: "Tovar",
        name: "MRW 1403000",
        address: "Cr 4ta. Cc El Llano Nivel Pb Local 4 Sector El Llano Tovar, Edo. Merida.",
        code: "1403000",
      },
      {
        id: "5iNtfPslZ4",
        city: "Tucani",
        name: "MRW TUCANIZON",
        address: "Carretera Panamericana , Sector El Carmen,galpon 1, Al Lado De La Estacion De Servicio El Indio.tucanizon Edo Merida.",
        code: "1407000",
      },
    ]
  },
  {
    name: "Nueva Esparta",
    agencies: [
      {
        id: "VRtKi8VfS1",
        city: "Juan Griego",
        name: "MRW JUAN GRIEGO",
        address: "Calle Guevara, Nro 12 B, Entre Calles La Marina Y Marcano, Diagonal A Comercial Juan Griego.",
        code: "1702000",
      },
      {
        id: "VRtKi8VfS2",
        city: "San Juan Bautista",
        name: "MRW EL ESPINAL",
        address: "Avenida Juan Bautista Arismendi, Sector La Encrucijada Del Espinal Via San Juan Bautista, A 100 Metros De La Regional El Espinal.",
        code: "1702100",
      },
      {
        id: "VRtKi8VfS3",
        city: "Pampatar",
        name: "MRW JOVITO VILLALBA",
        address: "Av. Jovito Villalba, Local Estacion De Servicio Maneiro, Nro 9493, Urb San Lorenzo, Pampatar. Estado Nueva Esparta.",
        code: "1704000",
      },
      {
        id: "VRtKi8VfS4",
        city: "Porlamar",
        name: "MRW NUEVA CADIZ",
        address: "Avenida Juan Bautista Arismendi, Edificio Ultramar , Local 2, Sector Los Cocos, Diagonal A Citroen. Porlamar.",
        code: "1705000",
      },
      {
        id: "VRtKi8VfS5",
        city: "Porlamar",
        name: "MRW PORLAMAR CENTRO",
        address: "Calle Velazquez Con Esquina Fajardo, Casa S/n, Sector Centro Porlamar, Nueva Esparta.",
        code: "1706000",
      },
      {
        id: "VRtKi8VfS6",
        city: "Villa Rosa",
        name: "MRW VILLA ROSA",
        address: "Av Juan Bautista Arismendi, Local Galpon Seven-art P.b, Sector San Antonio Norte-villa Rosa, Edo. Nueva Esparta.",
        code: "1707000",
      },
    ]
  },
  {
    name: "Portuguesa",
    agencies: [
      {
        id: "8gYYUc4e51",
        city: "Acarigua",
        name: "MRW ACARIGUA",
        address: "Calle 22. Entre Avenidas Libertador Y Alianza Diagonal A La Panaderia Trebol, Acarigua Centro. Edo. Portuguesa. Codigo Postal 3301.",
        code: "1801000",
      },
      {
        id: "8gYYUc4e52",
        city: "Acarigua",
        name: "MRW CENTRO LOS LLANOS",
        address: "Calle 31 Con Av 28 C.c Los Llanos Local 5 Planta Baja. Codigo Postal 3301.",
        code: "1804000",
      },
      {
        id: "8gYYUc4e53",
        city: "Guanare",
        name: "MRW GUANARE",
        address: "Av Jose Maria Vargas, C.C. Revica Galpon Nro 4. Sector El Cambio Guanare Portuguesa. Codigo Postal 3350.",
        code: "1800000",
      },
      {
        id: "8gYYUc4e54",
        city: "Turén",
        name: "MRW TUREN",
        address: "Av 6, Esquina Calle 5, Sector Centro.",
        code: "1802000",
      },
    ]
  },
  {
    name: "Sucre",
    agencies: [
      {
        id: "RYPVXoYPl1",
        city: "Carúpano",
        name: "MRW CARUPANO",
        address: "Av Universitaria Edif Prosein Piso Mezanina Local B Sector Los Molinos Carupano, Edo Sucre.",
        code: "1901000",
      },
      {
        id: "RYPVXoYPl2",
        city: "Cumaná",
        name: "MRW CUMANA",
        address: "Calle Marino, Edf Tunimiquire Local No 01, Cumana.",
        code: "1900000",
      },
      {
        id: "RYPVXoYPl3",
        city: "Cumaná",
        name: "MRW CUMANA URDANETA",
        address: "4ta Transversal De La Avenida Gran Mariscal. Edificio Cue, P.b. Local 1.",
        code: "1902000",
      },
    ]
  },
  {
    name: "Trujillo",
    agencies: [
      {
        id: "7HV0GCvYq1",
        city: "Boconó",
        name: "MRW BOCONO",
        address: "Av. Miranda C/c C. Andres Bello. Local 2. Sector Centro Bocono Edo Trujillo.",
        code: "2103000",
      },
      {
        id: "7HV0GCvYq2",
        city: "Carache",
        name: "MRW CARACHE",
        address: "Av. Principal Casa S/n Sector Palo Negro, Carache Estado Trujillo.",
        code: "2102000",
      },
      {
        id: "7HV0GCvYq3",
        city: "Sabana De Mendoza",
        name: "MRW SABANA DE MENDOZA",
        address: "Avda Las Flores Entre Calles Piar Y Comercio Local Nro A-4 Sabana De Mendoza Mcpio Sucre Estado Trujillo.",
        code: "2106000",
      },
      {
        id: "7HV0GCvYq4",
        city: "Trujillo",
        name: "MRW TRUJILLO",
        address: "Calle Regularizacion Sector Centro, C.C. Geminis Center, Pb Local 3; Frente A La Plaza Bolivar, Trujillo.",
        code: "2100000",
      },
      {
        id: "7HV0GCvYq5",
        city: "Valera",
        name: "MRW VALERA",
        address: "Calle 5 Entre Av. Bolivar Y 9. Edif. Profesional Don Pepe. Pb, Local Mrw. Valera Estado Trujillo.",
        code: "2101000",
      },
      {
        id: "7HV0GCvYq6",
        city: "Valera",
        name: "MRW VALERA CENTRO",
        address: "Ubicado En Av 12 Entre Calles. 8 Y 9 Edf Beatriz Local , A Una Cuadra De La Plaza Bolivar. Valera Estado Trujillo.",
        code: "2105000",
      },
      {
        id: "7HV0GCvYq7",
        city: "Valera",
        name: "MRW VALERA LOS LIMONCITOS",
        address: "Av. Bolivar, Esquina Con Calle 22, Edif. Residencias Trinitarias Ii, P.b., Local B, Sector Los Limoncitos. Frente A Mcdonalds , Valera, Edo. Trujillo.",
        code: "2104000",
      },
    ]
  },
  {
    name: "Táchira",
    agencies: [
      {
        id: "n3R3PHrTr1",
        city: "Capacho",
        name: "MRW SAN CRISTOBAL CENTRO",
        address: "7ma Av Entre Calle 5 Y 6 C.c. Partenon , Nivel P.b Local Nro 3 Diagonal A La Torre Union, A Cuadra Y Media De La Plaza Bolivar, Sector Centro, San Cristobal Estado Tachira.",
        code: "2010000",
      },
      {
        id: "n3R3PHrTr2",
        city: "Colón",
        name: "MRW SAN JUAN DE COLON",
        address: "Carrera 5 Esquina Calle 7 # 4-79 San Juan De Colon Edo Tachira.",
        code: "2012000",
      },
      {
        id: "n3R3PHrTr3",
        city: "El Piñal",
        name: "MRW EL PIÑAL",
        address: "Calle 1 Via La Morita Zona Comercial El Mirador, El Pinal Municipio Fernandez Feo, Edo. Tachira.",
        code: "2006000",
      },
      {
        id: "n3R3PHrTr4",
        city: "La Fría",
        name: "MRW LA FRIA",
        address: "Carrera 11 Entre Calles 5 Y 6 Nro 4-49 Municipio Garcia De Hevia La Fri+a La Fria Edo. Tachira.",
        code: "2003000",
      },
      {
        id: "n3R3PHrTr5",
        city: "La Grita",
        name: "MRW LA GRITA",
        address: "Av Fco De Caceres Con Calle 6, Diagonal Al Colegio Sta Rosa De Lima, Casa Nro 7-9 La Grita Edo Tachira La Grita Edo. Tachira.",
        code: "2004000",
      },
      {
        id: "n3R3PHrTr6",
        city: "Paramillo",
        name: "MRW PARAMILLO",
        address: "Av Los Agustinos Esq Calle 4 Local Nro 3-70 Urb El Lobo, Sector Paramillo San Cristobal.",
        code: "2011000",
      },
      {
        id: "n3R3PHrTr7",
        city: "Rubio",
        name: "MRW RUBIO",
        address: "Centro Comercial Venezia Frente A La Plaza Bolivar De Rubio Sector Centro Locales 6 Y 7, Estado Tachira.",
        code: "2005000",
      },
      {
        id: "n3R3PHrTr8",
        city: "San Antonio Del Táchira",
        name: "MRW SAN ANTONIO DEL TACHIRA",
        address: "Av Venezuela Con Calle 7 Edif Real Local N 7-09 Sector Centro, A Tres Cuadras De La Aduana Principal.",
        code: "2002000",
      },
      {
        id: "n3R3PHrTr9",
        city: "San Cristóbal",
        name: "MRW BARRIO OBRERO",
        address: "Carrera 22 Esquina Pasaje Pirineos Nro 21-97 Sector Barrio Obrero, San Cristobal Estado Tachira. Codigo Postal 5001.",
        code: "2008000",
      },
      {
        id: "n3R3PHrTr10",
        city: "San Cristóbal",
        name: "MRW BARRIO OBRERO - CRA. 20",
        address: "Barrio Obrero, Calle 10, Cra. 20, Nro. 9-108, Local 6, Frente A Licoreria 9 Con 19, San Cristobal, Edo. Tachira.",
        code: "2000000",
      },
      {
        id: "n3R3PHrTr11",
        city: "San Cristóbal",
        name: "MRW SAN CRISTOBAL CONCORDIA",
        address: "Calle 4bis C/C Crrs. 6 Y 7. Edif. Ramirez. P.b. Local 1, Detras Del Diario La Nacion. La Concordia. San Cristobal, Estado Tachira.",
        code: "2001000",
      },
      {
        id: "n3R3PHrTr12",
        city: "Táriba",
        name: "MRW TARIBA",
        address: "Calle 8 Con Carrera 8 Casa Nro 7-87 Local 2, A Dos Cuadras Del Hospital San Antonio. Sector Tariba, Tachira.",
        code: "2007000",
      },
      {
        id: "n3R3PHrTr13",
        city: "Ureña",
        name: "MRW URENA",
        address: "Calle 5 Con Esquina Carrera 6, Edif. Sofi, P.b. Local 103, 104, 105, 106 Y 107, Barrio La Guajira. Urena, Estado Tachira",
        code: "2009000",
      },
    ]
  },
  {
    name: "Yaracuy",
    agencies: [
      {
        id: "iQ0lvWFtrY1",
        city: "Nirgua",
        name: "MRW NIRGUA",
        address: "Av. 5 Entre Calles 4 Y 5. Edif. Murcia, Local 3. Diagonal Al Banco Provincial, Sector Plaza Sucre. Nirgua. Codigo Postal 3205.",
        code: "2301000",
      },
      {
        id: "iQ0lvWFtrY2",
        city: "San Felipe",
        name: "MRW SAN FELIPE",
        address: "Calle 16 Con 2 Y 3 Av, Detras Del Liceo Cecilia Mujica, Edf. Rospier, Al Lado De La Farmacia Farmabanguar. Cpodigo Postal 3102",
        code: "2300000",
      },
      {
        id: "iQ0lvWFtrY3",
        city: "Yaritagua",
        name: "MRW YARITAGUA",
        address: "Calle 17 Entre Carreras 7 Y 8 Local S/n, Diagonal Al Registro Civil. Sector Centro Yaritagua - Yaracuy. Codigo Postal 3230.",
        code: "2303000",
      },
    ]
  },
  {
    name: "Zulia",
    agencies: [
      {
        id: "MFAUicyZLK1",
        city: "Cabimas",
        name: "MRW CABIMAS",
        address: "Av Intercomunal, Esquina Cumana Edif Intercumana Local N 02 Pb Cabimas Edo Zulia.",
        code: "2412000",
      },
      {
        id: "MFAUicyZLK2",
        city: "Caja Seca",
        name: "MRW CAJA SECA",
        address: "Nueva Bolivia Merida, Ctra. Panamericana, Sector La Chertoza, C.c Stilo, Planta Baja Local 2.",
        code: "2424000",
      },
      {
        id: "MFAUicyZLK3",
        city: "Ciudad Ojeda",
        name: "MRW CIUDAD OJEDA CENTRO",
        address: "Calle Faria Esq Calle Lara C.c Ted Nivel Pb Local 03 Sector Casco Central Ciudad Ojeda Edo. Zulia.",
        code: "2417000",
      },
      {
        id: "MFAUicyZLK4",
        city: "Ciudad Ojeda",
        name: "MRW CUIDAD OJEDA",
        address: "Av. Intercomunal Local Mrw Nro S/n Sector Las Morochas Frente A La Bomba Central, Ciudad Ojeda Zulia.",
        code: "2404000",
      },
      {
        id: "MFAUicyZLK5",
        city: "El Venado",
        name: "MRW EL VENADO",
        address: "Av. Independencia, Centro Comercial San Antonio (los Duartes), Local #01, Mene Grande; Municipio Baralt Del Estado Zulia.",
        code: "2416000",
      },
      {
        id: "MFAUicyZLK6",
        city: "Machiques",
        name: "MRW MACHIQUES",
        address: "Av. Artes Esq, Calle Paz, Frente Al Banco Agricola. Machiques Eso. Zulia.",
        code: "2408000",
      },
      {
        id: "MFAUicyZLK7",
        city: "Maracaibo",
        name: "MRW CIRCUNVALACION 2",
        address: "Parroquia Cecilio Acosta, Municipio Maracaibo, Av. 58 Circunvalacion Nro 2 Edif, Casa Saas Piso: Pb, Local 98e-164 Barrio Entre Calles 98e Y 99, Barrio Andres Eloy Blanco.",
        code: "2400100",
      },
      {
        id: "MFAUicyZLK8",
        city: "Maracaibo",
        name: "MRW COROMOTO",
        address: "Urbanizacion Coromoto, Avenida 40cc Villa Mall Pb Numero 161-44 Local 4. Frente A La Emisora Alegria Stereo. Maracaibo - Zulia.",
        code: "2406200",
      },
      {
        id: "MFAUicyZLK9",
        city: "Maracaibo",
        name: "MRW CURVA DE MOLINA",
        address: "Calle 79 Nro 92-58 Frente Al Modulo Libertador, Al Lado De La Ferreteria Ranye.",
        code: "2425000",
      },
      {
        id: "MFAUicyZLK10",
        city: "Maracaibo",
        name: "MRW LA CHINITA",
        address: "Av. 12 C/c 93 Padilla, Edif. Padilla, Local Nro 33 Sector Casco Central. Al Lado Del Centro De Literatura Cristiana, Maracaibo, Edo. Zulia.",
        code: "2413000",
      },
      {
        id: "MFAUicyZLK11",
        city: "Maracaibo",
        name: "MRW LOS OLIVOS",
        address: "Av 28 La Limpia Con Avenida 69 Local 69b-09 Sector Los Aceitunos Al Lado De La E/S Los Aceitunos.",
        code: "2400500",
      },
      {
        id: "MFAUicyZLK12",
        city: "Maracaibo",
        name: "MRW MANZANILLO",
        address: "Calle 10 La Union Con Av. 24, C.c. B & B, P.b. Local 2 Sector Manzanillo. Maracaibo, Edo. Zulia.",
        code: "2406000",
      },
      {
        id: "MFAUicyZLK13",
        city: "Maracaibo",
        name: "MRW MARACAIBO NORTE",
        address: "Av. Paul Moreno, Antigua Fuerzas Armadas Con Calle 20, Edif Milenium Casa Saas S/n, Pq: Raul Leonis, Maracaibo Edo Zulia.",
        code: "2400600",
      },
      {
        id: "MFAUicyZLK14",
        city: "Maracaibo",
        name: "MRW MBO INDIO MARA",
        address: "Calle 78 Dr Portillo Entre Av. 17 Y 18 No 17-35 Cc Don Julio Diagonal Al Banco Provincial, Sector El Paraiso.",
        code: "2401000",
      },
      {
        id: "MFAUicyZLK15",
        city: "Maracaibo",
        name: "MRW MBO IRAMA",
        address: "Av 5 Con Calle E Local Nro E-71 Sector 18 De Octubre, A Pocos Metros De Frenos Irazuca. Monte Claro Maracaibo Zulia.",
        code: "2414000",
      },
      {
        id: "MFAUicyZLK16",
        city: "Maracaibo",
        name: "MRW MBO LA LAGO",
        address: "Av 3e Entre Calles 72 Y 73 Edif Asociacion Zuliana De Ciegos Piso Pb Local 3, Sector La Lago Maracaibo Zulia.",
        code: "2423000",
      },
      {
        id: "MFAUicyZLK17",
        city: "Maracaibo",
        name: "MRW MBO LA LIMPIA",
        address: "	Av. 28 Edif. Rodriguez Y Barboza, Piso Pb Local 01,nro 14-54 Diagonal Al Hotel Maracaibo Suit. Sector La Limpia Maracaibo Estado Zulia.",
        code: "2400000",
      },
      {
        id: "MFAUicyZLK18",
        city: "Santa Bárbara Del Zulia",
        name: "MRW SANTA BARBARA DEL ZULIA",
        address: "Av 8 Casa Nro 5-127 Sector Bolivar, Santa Barbara Zulia.",
        code: "2415000",
      },
      {
        id: "MFAUicyZLK19",
        city: "Tía Juana",
        name: "MRW TIA JUANA",
        address: "Avenida Intercomunal De Tia Juana, Sector Ezequiel Zamora, Local # 1. Frente A Prodata Wire - Line. Tia Juana.",
        code: "2420000",
      },
    ]
  },

]