export const states = [
  {
    name: "Amazonas",
    agencies: [
      {
        id: "SvvtavRW4x",
        city: "Puerto Ayacucho",
        name: "ZOOM PUERTO AYACUCHO",
        address: "Av. Rio Negro, Centro Comercial Juncosa, Local 2-a.",
        code: "100",
      },
    ]
  },
  {
    name: "Anzoátegui",
    agencies: [
      {
        id: "56KEVGp7j4",
        city: "Anaco",
        name: "ALIADO ZOOM FV COMUNICACIONES, C.A.",
        address: "Sector Viento Fresco, Av. Jose Antonio Anzoatagui, C.c. Super Estacion , Nivel Pb, Local Nro. 09.",
        code: "2251",
      },
      {
        id: "56KEVGp7j5",
        city: "Anaco",
        name: "ZOOM ANACO",
        address: "Calle 5 De Julio, Edf. San Elias Nro 3-23b Pb. P.ref. Una Cuadra De Banesco.",
        code: "3",
      },
      // 
      {
        id: "Mm1xPb0xmS",
        city: "Barcelona",
        name: "ALIADO ZOOM MBE CUMANA (BARCELONA)",
        address: "Av.cristobal Colon Perimetal, Sec. El Diqui, C.c. Marina Plaza, Edif. D-3, Local P.b.-4.",
        code: "3857",
      },
      {
        id: "56KEgGp751",
        city: "Barcelona",
        name: "ALIADO ZOOM SEACAR ORIENTE 1702, C.A.",
        address: "	Calle Zulia De Barrio Sucre, Local 5 - C Barcelona Edo- Anzoategui.",
        code: "3050",
      },
      {
        id: "56KEVGp7j1",
        city: "Barcelona",
        name: "ALIADO ZOOM SUMINISTROS E INSUMOS INSUMEDIC C.A",
        address: "Boulevar 5 De Julio, Centro Comercial Isfra, Local 7n Barcelona.",
        code: "4026",
      },
      {
        id: "56KEVGp7j2",
        city: "Barcelona",
        name: "ZOOM BARCELONA",
        address: "Av. Intercomunal Jorge Rodriguez, C.c. Brisas Del Neveri, Local 04. P.ref. Frente A La Escuela De Ingenieria Ugma.",
        code: "106",
      },
      {
        id: "56KEVGp7j3",
        city: "Barcelona",
        name: "ZOOM CAMINO REAL",
        address: "Av Costanera Con Av Fuerzas Armadas C.c Camino Real Nivel Plaza Pb Local C11, Sector Nueva Barcelona.",
        code: "4058",
      },
      // 
      {
        id: "CNYLd0eZYn",
        city: "Cantaura",
        name: "ALIADO ZOOM IS INFOSISTEMAS, C.A.",
        address: "Av. Bolivar Cruce Con Calle Arismendi, Sector Centro Cantaura.",
        code: "2262",
      },
      // 
      {
        id: "56KEVGp7j7",
        city: "El Tigre",
        name: "ALIADO ZOOM PRINT SOLUTIONS EL TIGRE",
        address: "Calle 20 Sur, Cruce Con 5ta Carrera Bis.",
        code: "2345",
      },
      {
        id: "56KEVGp7j8",
        city: "El Tigre",
        name: "ZOOM EL TIGRE",
        address: "Av. Fco. De Miranda, Centro Comercial Flamingo, Pb. Locales A-07 Y A-08. P.ref. Al Lado De La Alcaldia.",
        code: "62",
      },
      // 
      {
        id: "56KEVGp7j6",
        city: "Lechería",
        name: "ALIADO ZOOM PREVIEW, C.A.",
        address: "Sector Casco Central Lecherias Carrera 5 Entre Calle 2 Y 3 Centro Empresarial 17-11 Local Pb-1.",
        code: "2051",
      },
      // 
      {
        id: "tEysGLqx5S",
        city: "Puerto La Cruz",
        name: "ALIADO ZOOM CENTRO INTEGRAL DE COMUNICACIONES LOS UDISTAS, C.A",
        address: "Av. Paseo Colon Edif. Hotel Rasil Piso, 1 Local Nro 02 Sector, Puerto La Cruz.",
        code: "3107",
      },
      {
        id: "F4d1bcPqwU",
        city: "Puerto La Cruz",
        name: "ALIADO ZOOM INVERSIONES Y ASOCIADOS ELBA C.A",
        address: "Calle Democracia Cruce Con Calle Juncal Local Terminal De Pasajeros Nro S/n,sector Casco Central.",
        code: "4064",
      },
      {
        id: "HtUBGjxTKD",
        city: "Puerto La Cruz",
        name: "ALIADO ZOOM MBE PUERTO LA CRUZ",
        address: "Calle Las Flores Con Calle Guaraguao, Centro Comercial Carabel, Planta Baja, Local 2.",
        code: "694",
      },
      {
        id: "zQrchXPDmz",
        city: "Puerto La Cruz",
        name: "ALIADO ZOOM MEGA PC SYSTEMS, C.A",
        address: "Av Municipal Cc Central Madeirense Nivel Pb Local 17,sector Pueblo Nuevo.",
        code: "4023",
      },
      {
        id: "HLgufvyqZF",
        city: "Puerto La Cruz",
        name: "ZOOM AMANA",
        address: "Calle Bolivar Cruce Con Calle Maneiro. Centro Comercial Amana Local Pb A-6.",
        code: "919",
      },
    ]
  },
  {
    name: "Apure",
    agencies: [
      {
        id: "POL0ZWtgh1",
        city: "Biruaca",
        name: "ALIADO ZOOM INVERSIONES CANARIAS II, C.A.",
        address: "Av. Las Acacias , Local N°. 2 , Sector Encrucijada De Biruaca Apure.",
        code: "2714",
      },
      {
        id: "POL0ZWtgh2",
        city: "San Fernando",
        name: "ZOOM SAN FERNANDO DE APURE",
        address: "Av. Carabobo Con Esquina Calle Cajuarito, Edf. Kassas, Local S/n.",
        code: "871",
      },
    ]
  },
  {
    name: "Aragua",
    agencies: [
      {
        id: "37I5iRZEO1",
        city: "Cagua",
        name: "ALIADO ZOOM COMERCIAL AMANI, C.A",
        address: "Calle Comercio Cruce Con Calle Sucre Edif Amani Piso Pb Local 104-70-17 Sector Centro Cagua.",
        code: "3460",
      },
      {
        id: "37I5iRZEO2",
        city: "Cagua",
        name: "ZOOM CAGUA",
        address: "Sector Centro, Calle Rondon C/c Calle Bermudez Nro 104-03-07, Local L-3.",
        code: "1266",
      },
      {
        id: "37I5iRZEO3",
        city: "Colonia Tovar",
        name: "ALIADO ZOOM INVERSIONES CASA COLONIA, C.A.",
        address: "Sector Plan De Moreno, Carretera Principal Plan De Moreno, C.c. Parque Moritz, Nivel 1, Local N1-3.",
        code: "1843",
      },
      {
        id: "37I5iRZEO4",
        city: "La Victoria",
        name: "ALIADO ZOOM ENVIOS RAPIDOS Y SEGUROS MORICHAL, C.A.",
        address: "Sector Centro Las Mercedes, Av. Victoria, C.c. Cilento, Nivel Pb, Local Nro. 8. (la Mora).",
        code: "2384",
      },
      {
        id: "37I5iRZEO5",
        city: "La Victoria",
        name: "ZOOM LA VICTORIA",
        address: "Calle Rivas Davila, C.c. Victoria Center, Primera Etapa, Nivel Planta Baja, Local A-6.",
        code: "1556",
      },
      {
        id: "37I5iRZEO6",
        city: "Maracay",
        name: "ALIADO ZOOM FAST DELIVERY, C.A.",
        address: "Av. Bermudez Edif. Del Pinto Piso 1 Local B, Urb. Bermudez.",
        code: "2466",
      },
      {
        id: "37I5iRZEO7",
        city: "Maracay",
        name: "ALIADO ZOOM TOTAL SOLUTIONS TOSOCA, C.A.",
        address: "Sector Nro. 03, Cana De Azucar, Av. Nro. 05, Local Nro. 13-c.",
        code: "2592",
      },
      {
        id: "37I5iRZEO8",
        city: "Maracay",
        name: "ALIADO ZOOM CANGURO EXPRESS 911, C.A.",
        address: "Zona La Cooperativa Maracay, Av. Ppal. La Cooperativa C/c Calle Urdaneta, Casa Nro. 7, Local Nro. 4.",
        code: "2588",
      },
      {
        id: "37I5iRZEO9",
        city: "Maracay",
        name: "ALIADO ZOOM CENTRO DE COPIADO Y REPRODUCCION D.M.M., C.A.",
        address: "Av 19 De Abrilcc Mercado Ateneo Pasillo F Local F-08 Sector Centro.",
        code: "2396",
      },
      {
        id: "37I5iRZE10",
        city: "Maracay",
        name: "ALIADO ZOOM CENTRO ESCUELA DE SISTEMAS E INFORMATICA, C.A.",
        address: "Av. Fuerzas Aereas C/c Av. Jose Casanova Godoy, Cc H Y Per Jumbo, Nivel Sotano.",
        code: "2294",
      },
      {
        id: "37I5iRZE11",
        city: "Maracay",
        name: "ALIADO ZOOM CORPORACION CALITRI, C.A.",
        address: "Av. Bermudez, Cruce Con Av. Aragua, C.c. Maracay Plaza, Nivel Planta Baja, Local 61-d.",
        code: "1703",
      },
      {
        id: "37I5iRZE12",
        city: "Maracay",
        name: "ALIADO ZOOM EPAC 2120, C.A.",
        address: "Av. Los Cedros Local, Nro.41, Barrio Lourdes, Maracay.",
        code: "3150",
      },
      {
        id: "37I5iRZE13",
        city: "Maracay",
        name: "ALIADO ZOOM EXPORT EXPRESS, C.A.",
        address: "Av Fuerzas Aereas, Urb Mario Briceño Iragorri, Nro 93.",
        code: "881",
      },
      {
        id: "37I5iRZE14",
        city: "Maracay",
        name: "ALIADO ZOOM EXPRESS CORPORATION JM, C.A.",
        address: "Av Bolivar Cc Ipsfa Nivel P. Central Local Pcb-15 Sector Maracay.",
        code: "3546",
      },
      {
        id: "37I5iRZE15",
        city: "Maracay",
        name: "ALIADO ZOOM FMJ CURIER, C.A.",
        address: "Calle Sucre Norte Local Nro 83-5 Urb Calicanto.",
        code: "1166",
      },
      {
        id: "37I5iRZE16",
        city: "Maracay",
        name: "ALIADO ZOOM INVERSIONES CASTILLO 2010, C.A.",
        address: "Sector El Limon, Av. Universidad,c.c. El Limon, Nivel Pb, Local Nro. 03.",
        code: "1195",
      },
      {
        id: "37I5iRZE17",
        city: "Maracay",
        name: "ALIADO ZOOM MBE MARACAY",
        address: "Av Las Delicias Local C.c Y Hotel Paseo Las Delicias Nivel Avenida Nro 2-av-19 Urb Base Aragua.",
        code: "702",
      },
      {
        id: "37I5iRZE18",
        city: "Maracay",
        name: "ALIADO ZOOM SERVICE EXPRESS FEDERAL, C.A.",
        address: "Av. Mariqo Sur, Centro Empresarial Uniaragua, Planta Baja, Local 1.",
        code: "720",
      },
      {
        id: "37I5iRZE19",
        city: "Maracay",
        name: "ZOOM LAS DELICIAS",
        address: "Av Las Delicias Centro Empresarial Europa Piso 1, Local 1-18",
        code: "4027",
      },
      {
        id: "37I5iRZE20",
        city: "Maracay",
        name: "ZOOM MARACAY",
        address: "Av. Anthon Phillips, Zona Industrial San Vicente, Centro Comercial San Vicente, Local 2. P.ref. Al Lado De Empresas Saviran.",
        code: "87",
      },
      {
        id: "37I5iRZE21",
        city: "Maracay",
        name: "ZOOM MARACAY AV. MIRANDA",
        address: "Av. Miranda Oeste, Cruce Con Calle Campo Elias Nro 165.",
        code: "805",
      },
      {
        id: "37I5iRZE22",
        city: "Maracay",
        name: "ZOOM PACIFICO",
        address: "Av. Bolivar Oeste, Centro Comercial Pacifico, Planta Baja Local Nro 6. P.ref. A 50 Metros Del C.c. Parque Aragua. Donde Se Encuentra El Colegio De Contadores Publicos).",
        code: "1140",
      },
      {
        id: "37I5iRZE23",
        city: "Santa Cruz De Aragua",
        name: "ALIADO ZOOM BASMELCA ARAGUA C.A.",
        address: "Av 02 Casa Parcela B-17-a Y B-17-b Zona Industrial Santa Cruz.",
        code: "3966",
      },
      {
        id: "37I5iRZE33",
        city: "Santa Rita",
        name: "ALIADO ZOOM INVERSIONES Y SERVICIOS JM, C.A.",
        address: "Av Intercomunal Maracay-turmero Cc Intercomunal Center Nivel Local 1-7,sector La Morita.",
        code: "2485",
      },
      {
        id: "37I5iRZE24",
        city: "Turmero",
        name: "ALIADO ZOOM ARACOMP SYSTEMS, C.A.",
        address: "Sector Centro Turmero, Calle Urdaneta Casa Nro. 16 Y Nro. 1.",
        code: "2351",
      },
      {
        id: "37I5iRZE25",
        city: "Turmero",
        name: "ALIADO ZOOM CIUDAD DE COMUNICACIONES, C.A.",
        address: "Carretera Nacional Turmero - Cagua Centro Comercial Paseo Los Laureles Nivel Pb Local 4. Urb. La Encrucijada.",
        code: "1221",
      },
      {
        id: "37I5iRZE26",
        city: "Villa De Cura",
        name: "ALIADO ZOOM VIAJES Y TURISMO GRAN TPUY, C.A.",
        address: "Calle Sucre Con Aduana, C.c. Villa Hermosa, Local 39.",
        code: "1638",
      },
    ]
  },
  {
    name: "Barinas",
    agencies: [
      {
        id: "0mhSQfCPe1",
        city: "Barinas",
        name: "ALIADO ZOOM BIG BEN SERVICIOS EMPRESARIALES, C.A.",
        address: "Alto Barinas Norte, Avenida Colombia, Local 80-c, Frente Al Golfito.",
        code: "1753",
      },
      {
        id: "0mhSQfCPe2",
        city: "Barinas",
        name: "ALIADO ZOOM INVERSIONES Y SERVICIOS CONSTRUC EXPRESS, C.A.",
        address: "Av. Venezuela Con Calle Justicia Local, Nro. 127 B-3, Urb, Alto Barinas Sur Barinas.",
        code: "1904",
      },
      {
        id: "0mhSQfCPe3",
        city: "Barinas",
        name: "FARMACIA BETANIA C.A.",
        address: "Avenida Los Llanos C.c Sion Pb Local 5 Alto Barinas Sur Farmacia Betania C.a (qiaris Farmacia).",
        code: "3465",
      },
      {
        id: "0mhSQfCPe4",
        city: "Barinas",
        name: "ZOOM BARINAS",
        address: "Av. Elias Cordero, N° 1- 120. P.ref. Frente A Suelapiel.",
        code: "6",
      },
      {
        id: "0mhSQfCPe6",
        city: "Barinas",
        name: "ZOOM BARINAS CENTRO",
        address: "Sector Barrio Obrero, Calle Camejo Entre Avenidas Montilla Y Olmedilla, Edificio Los Hermanos.",
        code: "1543",
      },
      {
        id: "0mhSQfCPe7",
        city: "Santa Barbara De Barinas",
        name: "ALIADO ZOOM INVERSIONES CARLEX, C.A.",
        address: "Sector Pueblo Viejo, Carrera 5, Entre Calles 9 Y 10.",
        code: "1169",
      },
      {
        id: "0mhSQfCPe8",
        city: "Socopo",
        name: "ALIADO ZOOM ARUVEN SERVICIOS, C.A.",
        address: "Calle 1 Entre Carreras 4 Y 5 Local Nro 4-36 Sector Las Flores Socopo Barinas",
        code: "3096",
      },
    ]
  },
  {
    name: "Bolívar",
    agencies: [
      {
        id: "QZ3nhGlbo1",
        city: "Ciudad Bolívar",
        name: "ALIADO ZOOM 1 DIGITAL, C.A.",
        address: "Sector Germania, Av. Germania, C.c. Los Proceres Nivel Pb, Local Anexo Estacionamiento.",
        code: "1810",
      },
      {
        id: "QZ3nhGlbo2",
        city: "Ciudad Bolívar",
        name: "ALIADO ZOOM MN LLAMADAS, C.A. (PASEO MENESES)",
        address: "Sector Germania, Av. Germania, C.C. Los Proceres Nivel Pb, Local Anexo Estacionamiento.",
        code: "1178",
      },
      {
        id: "QZ3nhGlbo3",
        city: "Ciudad Bolívar",
        name: "ZOOM CIUDAD BOLIVAR",
        address: "Av. Jesus Soto Con Calle Caura, C.c. Tepuy, Local 1 Y 2, Pb.",
        code: "56",
      },
      {
        id: "QZ3nhGlbo4",
        city: "El Callao",
        name: "ALIADO ZOOM LA HORMIGA MULTISERVICIOS, C.A. (EL CALLAO)",
        address: "Calle La Paz , Frente Al Parque Infantil Victoria Torrealba Local S/n.",
        code: "2586",
      },
      {
        id: "QZ3nhGlbo5",
        city: "Puerto Ordaz",
        name: "ALIADO ZOOM CONSULTORES INTEGRALES EMPRESARIALES GIAGIAKOS C.A",
        address: "Ctra Tocoma, Con Calle Caura Cc C.c Torre Caura Nivel Sotano Local 4 Sector Alta Vista.",
        code: "3171",
      },
      {
        id: "QZ3nhGlbo6",
        city: "Puerto Ordaz",
        name: "ALIADO ZOOM GRUPO PF, C.A.",
        address: "Urb. Alta Vista, Av. Prolongacion, Av. Las Americas, C.c. Orinokia Mall Nivel Plaza, Santo Tome Local Pb-04.",
        code: "1809",
      },
      {
        id: "QZ3nhGlbo7",
        city: "Puerto Ordaz",
        name: "ALIADO ZOOM MBE GUAYANA",
        address: "Av. Guayana,alta Vista,torre Colon, Planta Baja,locales 01 Y 02.",
        code: "705",
      },
      {
        id: "QZ3nhGlbo8",
        city: "Puerto Ordaz",
        name: "ALIADO ZOOM REGION 416, C.A.",
        address: "Av. Monsenor Zabaleta, Edf. Atlantico, Pb., Local 1.",
        code: "775",
      },
      {
        id: "QZ3nhGlbo9",
        city: "Puerto Ordaz",
        name: "ZOOM PUERTO ORDAZ",
        address: "Sector Unare, Zona Industrial I, Calle Tunapuy, P.ref. Diagonal Al Tigasco.",
        code: "109",
      },
      {
        id: "QZ3nhGlb10",
        city: "Puerto Ordaz",
        name: "ZOOM TAQUILLA CC ARTICA",
        address: "Centro Comercial Artica, Carrera Guasipati, Locales 5 Y 6. Centro De Puerto Ordaz. Al Lado Del Banco De Venezuela Y Frente A Cosmeticos Genesis.",
        code: "1206",
      },
      {
        id: "QZ3nhGlb11",
        city: "San Felix",
        name: "ZOOM SAN FELIX",
        address: "Sector El Roble, Av. Morena Mendoza, Centro Comercial La Cariñosa, Local C.",
        code: "1207",
      },
      {
        id: "QZ3nhGlb12",
        city: "Upata",
        name: "ALIADO ZOOM CELULAR PING I, C.A.",
        address: "Calle Ricaurte Cruce Con Union, Edificio Franzul, Local Comercial Nro 2, Planta Baja.",
        code: "1446",
      },
      {
        id: "QZ3nhGlb13",
        city: "Upata",
        name: "ALIADO ZOOM COPIADOS R.G, C.A",
        address: "Av Bicentenario Diagonal Calle 19 De Abril Cc El Datil Nivel Pb Local S/n Sector Centro.",
        code: "4015",
      },
    ]
  },
  {
    name: "Carabobo",
    agencies: [
      {
        id: "LcvMMP91T1",
        city: "Guacara",
        name: "ALIADO ZOOM D.S. CONEXIONES, C.A.",
        address: "Carretera Nacional Guacara Los Guayos, Centro Comercial Central Guacara Pb Local 18 Y 20.",
        code: "1624",
      },
      {
        id: "LcvMMP91T2",
        city: "Guacara",
        name: "ALIADO ZOOM MEKY & E2 INVERSIONES, C.A.",
        address: "Calle Piar C.c Guacara Plaza Nivel Pb Local Pb-09.",
        code: "1663",
      },
      {
        id: "LcvMMP91T3",
        city: "Los Guayos",
        name: "ALIADO ZOOM COMERCIALIZADORA 323, C.A.",
        address: "Calle Paez Entre Bruzual Y Negro Primero, Local A-01.",
        code: "1250",
      },
      {
        id: "LcvMMP91T4",
        city: "Puerto Cabello",
        name: "ZOOM PUERTO CABELLO",
        address: "Primera Calle Segrestaa, Edificio Enna, Pb., Local 26 Y 27.p.ref. Diagonal A La Cruz Roja.",
        code: "101",
      },
      {
        id: "LcvMMP91T5",
        city: "Valencia",
        name: "ALIADO ZOOM ALLIANZ EXPRESS, C.A. SECTOR ROJAS QUEIPO.",
        address: "Calle Rojas Queipo,nro 102-25, Local Nro 02,con Andres Eloy Blanco.",
        code: "1050",
      },
      {
        id: "LcvMMP91T6",
        city: "Valencia",
        name: "ALIADO ZOOM INVERSIONES DAMOVE C.A",
        address: "Avenida Victoria,nivel Planta Baja Vt4c1,centro Comercial Concepto La Viña.",
        code: "2723",
      },
      {
        id: "LcvMMP91T7",
        city: "Valencia",
        name: "ALIADO ZOOM ENVIOPASS, C.A.",
        address: "Av Salvador Feo La Cruz Este-oeste Edif World Trade Center Piso Mezzanina Local Lcm-1, Caserio MaÑongo Naguanagua Valencia.",
        code: "4024",
      },
      {
        id: "LcvMMP91T8",
        city: "Valencia",
        name: "ALIADO ZOOM ENVIOS Y DOCUMENTOS EXPRESS 21, C.A.",
        address: "Calle 119 Casa Nro 114-599 Urb Agua Blanca.",
        code: "3996",
      },
      {
        id: "LcvMMP91T9",
        city: "Valencia",
        name: "ALIADO ZOOM GALEVISION C.A.",
        address: "Calle 137 Cc La Galeria Nave A Nivel Pb Local 1-a6,urb Camoruco.",
        code: "4046",
      },
      {
        id: "LcvMMP9110",
        city: "Valencia",
        name: "ALIADO ZOOM GRUPO MARPETH, C.A.",
        address: "Sector San Diego, Av. Don Julio Centeno, C.C. San Diego (fin De Siglo), Nivel Galeria Nro. 3, Local Nro. 1 Y Nro. 2.",
        code: "2342",
      },
      {
        id: "LcvMMP9111",
        city: "Valencia",
        name: "ALIADO ZOOM INTERNATIONAL BOX SERVICES IBS, C.A. (SERVIBOX) (EL VIÃ‘EDO)",
        address: "Urb. El Trigal Norte Centro Comercial Patio Trigal, Tercera Nave Local 502-a.",
        code: "890",
      },
      {
        id: "LcvMMP9112",
        city: "Valencia",
        name: "ALIADO ZOOM INVERSIONES G-MARY, C.A.",
        address: "Av Nro.91 (avenida Michelena) Casa Nro. 90-63 Frente A La Clinica Santa Monica.",
        code: "2176",
      },
      {
        id: "LcvMMP9113",
        city: "Valencia",
        name: "ALIADO ZOOM INVERSIONES STALLONE, C.A.",
        address: "Valencia Center Pb, Local Nro 38, Al Frente Del Colegio Republica Del Peru, Detras Del Registro Civil.",
        code: "1419",
      },
      {
        id: "LcvMMP9114",
        city: "Valencia",
        name: "ALIADO ZOOM LEYMA INVERSIONES, C.A.",
        address: "Av Henry Ford Cc Paseo Las Inductrias Nivel Pb Local 7,zona Industrial Sur.",
        code: "2216",
      },
      {
        id: "LcvMMP9115",
        city: "Valencia",
        name: "ALIADO ZOOM MANINO EXPRESS SERVICES, C.A.",
        address: "Av 73 Humberto Celli Nro 84-50 Local 17 Centro Comercial Metro Sur Zona Industrial Municipal Norte.",
        code: "3462",
      },
      {
        id: "LcvMMP9116",
        city: "Valencia",
        name: "ALIADO ZOOM MBE ZONA INDUSTRIAL II",
        address: "Av. Luis Ernesto Branger Zona Industrial Municipal Sur Conj. Empresarial Entrada F Pb5.",
        code: "699",
      },
      {
        id: "LcvMMP9117",
        city: "Valencia",
        name: "ALIADO ZOOM OMEGA COLORS, C.A.",
        address: "Sector, Flor Amarillo Valencia, Av. Nro. 107-c, Local C.c. La Fundacion Nro. 1.",
        code: "1905",
      },
      {
        id: "LcvMMP9118",
        city: "Valencia",
        name: "ALIADO ZOOM PUNTO POST, C.A. (SAN DIEGO)",
        address: "Av. Boulevard Norte 102 Centro Comercial Boulevard Norte Local Nro. 3 Urb. San Diego.",
        code: "361",
      },
      {
        id: "LcvMMP9119",
        city: "Valencia",
        name: "ALIADO ZOOM RAPIDOS COURIER ETC, C.A.",
        address: "Barrio Entimio Rivas, Av. Nro. 93, Lisandro Alvarado, Casa Nro. 90-31, Local Nro. 02.",
        code: "2352",
      },
      {
        id: "LcvMMP9120",
        city: "Valencia",
        name: "ALIADO ZOOM SERVICIOS MENSAEXPRESS, C.A.",
        address: "Av. Bolivar Local Nro. 2 Sector Centro Montalban.",
        code: "1826",
      },
      {
        id: "LcvMMP9121",
        city: "Valencia",
        name: "ALIADO ZOOM TODO ENVIOS VALENCIA, C.A",
        address: "Av 102 Monte De Oca Calle 24 De Junio Y Calle Girardot Nro Civico 96-24 Casa Nro 5-a.",
        code: "4038",
      },
      {
        id: "LcvMMP9122",
        city: "Valencia",
        name: "ALIADO ZOOM TU CARGA EXPRESS, C.A. CAMORUCO",
        address: "Sector Camoruco, Calle San Jorge, C.C. Caribbean Plaza, Pb., Local 171, Modulo 8.",
        code: "1106",
      },
      {
        id: "LcvMMZ9153",
        city: "Valencia",
        name: "ALIADO ZOOM VIT PUBLICIDAD, C.A.",
        address: "Calle Colombia Con Soublette, Centro Comercial Fiera Mosca, Nivel Pb., Local 2.",
        code: "1319",
      },


      {
        id: "LcvMMP9123",
        city: "Valencia",
        name: "ZOOM AV. BOLIVAR NORTE",
        address: "Av. Bolivar Norte, Edf. Don Enrique Pb. P.ref. Frente A La Funeraria La Superior A 100 Mts Del Ateneo De Valencia.",
        code: "137",
      },
      {
        id: "LcvMMP9124",
        city: "Valencia",
        name: "ZOOM C.C METROPOLIS",
        address: "Autopista Regional Del Centro. Entrada De Valencia, Al Lado De Makro.centro Comercial Metropolis Nivel Cielo, Local A1-300b",
        code: "4061",
      },
      {
        id: "LcvMMP9125",
        city: "Valencia",
        name: "ZOOM VALENCIA",
        address: "Av. Este Oeste Con Calle 97, Urbanizacion San Diego, Parque Comercial Industrial Castillito Parcela L-70 Y L-78.",
        code: "136",
      },
    ]
  },
  {
    name: "Cojedes",
    agencies: [
      {
        id: "fF1agMUxK1",
        city: "San Carlos",
        name: "ZOOM PUERTO AYACUCHO",
        address: "Av. Bolivar Cruce Con Calle Silva, Centro Comercial Colavita, Planta Baja, Locales L1 Y L2.",
        code: "939",
      },
    ]
  },
  {
    name: "Delta Amacuro",
    agencies: [
      {
        id: "d6IpOUBte1",
        city: "Tucupita",
        name: "ALIADO ZOOM TERABYTES COMPUTER, C.A.",
        address: "Calle La Paz Local Nro S/n Sector Centro Tucupita.",
        code: "1159",
      },
    ]
  },
  {
    name: "Distrito Capital",
    agencies: [
      {
        id: "WhIt3MXNL1",
        city: "Caracas",
        name: "ALIADO ZOOM SHIPNET EL RECREO",
        address: "Av. Venezuela, Centro Comercial Galerias El Recreo. Nivel Avenida. Local Av-1c.",
        code: "249",
      },
      {
        id: "WhIt3MXNL2",
        city: "Caracas",
        name: "ALIADO ZOOM SHIPNET C.C. GALERIAS PRADOS DEL ESTE",
        address: "Av. Ppal. De Prados Del Este. Ctro. Comercial Galerias Prados Del Este. Nivel Pa. Local 39.",
        code: "238",
      },
      {
        id: "WhIt3MXNL3",
        city: "Caracas",
        name: "ALIADO ZOOM SHIPNET MANZANARES",
        address: "Av. Principal C.C Manzanares Ii Nivel Mirador Local M104.",
        code: "1313",
      },
      {
        id: "WhIt3MXNL4",
        city: "Caracas",
        name: "ALIADO ZOOM SHIPNET SANTA FE",
        address: "Av. Jose Maria Vargas. Ctro Comercial Santa Fe. Nivel C-3. Local 68, Urb Santa Fe Norte.",
        code: "142",
      },
      {
        id: "WhIt3MXNL5",
        city: "Caracas",
        name: "ALIADO ZOOM MORGAF INVERSIONES 777,C.A. (La Candelaria)",
        address: "Urb. La Candelaria, Av. Andres Eloy Blanco, Entre Av. Sur Nro. 25 Y Av.esquina La Mansion.edf. Morelos. Piso Pb.local Nro. 1 . (al Lado Del Seniat -plaza Morelos).",
        code: "2709",
      },
      {
        id: "WhIt3MXNL6",
        city: "Caracas",
        name: "ALIADO ZOOM CIUDAD POSTAL",
        address: "Av Este 2. Tracabordo A Puente Yanez, Edif. Res. Yanoral, P.b. La Candelaria.",
        code: "510",
      },
      {
        id: "WhIt3MXNL7",
        city: "Caracas",
        name: "ALIADO ZOOM CONTRATACIONES ALBA C.A (LA TAHONA)",
        address: "Avenida La Guairita Calle Reyna, Instituto Universitario Avepane, Urb La Tahona.",
        code: "4037",
      },
      {
        id: "WhIt3MXNL8",
        city: "Caracas",
        name: "ALIADO ZOOM CORPORACION ADWE, C.A.",
        address: "Calle Colombia, Entre Cristo Y Magallanes, Urb. Nueva Caracas- Catia, Edificio S/n, Piso Pb., Local Unico.",
        code: "1485",
      },
      {
        id: "WhIt3MXNL9",
        city: "Caracas",
        name: "ALIADO ZOOM CRISTALES SUR AMERICA, C.A.",
        address: "Esq. Muerto A Pelaez, Casa Nro. 116, Zona Parroquia Santa Rosalia.",
        code: "2984",
      },
      {
        id: "WhIt3MXN10",
        city: "Caracas",
        name: "ALIADO ZOOM DISTRIBUIDORA PULI, C.A.",
        address: "Av. Fuerzas Armadas Norte, Esq. San Jose A San Luis, Edf. Residencia San Jose.",
        code: "1382",
      },
      {
        id: "WhIt3MXN11",
        city: "Caracas",
        name: "ALIADO ZOOM DIGITAL PARAISO",
        address: "Av. Los Samanes, C.C. Euro, Nivel Pb, Local Nro. 12.",
        code: "2704",
      },
      {
        id: "WhIt3MXN12",
        city: "Caracas",
        name: "ALIADO ZOOM ENCOMIENDAS GALLERY 55, C.A.",
        address: "Calle Razetti, Urb. Los Chaguaramos, Quinta Centro Profesional Los Chaguaramos Pb.",
        code: "1127",
      },
      {
        id: "WhIt3MXN13",
        city: "Caracas",
        name: "ALIADO ZOOM GRUPO FIGUE, C.A. AV LIBERTADOR.",
        address: "Av. Libertador Con Calle Negrin , C.c. Libertador, Local Nro. 13.",
        code: "2768",
      },
      {
        id: "WhIt3MXN14",
        city: "Caracas",
        name: "ALIADO ZOOM IMPRESION,IMAGEN Y POP 2205 C.A.",
        address: "Av. Francisco De Miranda Edificio Centro Empresarial Don Bosco Piso P.b Local 2. Los Cortijos De Lourdes.",
        code: "1193",
      },
      {
        id: "WhIt3MXN15",
        city: "Caracas",
        name: "ALIADO ZOOM INSTALL COMPUTER, C.A.",
        address: "Av. Principal De Bello Monte, Entre Av. Leonardo Da Vici Y Av. Lincoln. Ctro. Comercial Bello Monte. P.b. Local Nro. 10. Bello Monte.",
        code: "728",
      },
      {
        id: "WhIt3MXN16",
        city: "Caracas",
        name: "ALIADO ZOOM INVERSIONES CAPITAL EXPRESS 2014, C.A. (Chacao)",
        address: "Calle Nro 3 Monsenor Juan Grilc Rezman, Qta. Silvia Nro 309, Local Nro 5 Chacao.",
        code: "1623",
      },
      {
        id: "WhIt3MXN17",
        city: "Caracas",
        name: "ALIADO ZOOM INVERSIONES JETES, C.A.",
        address: "Av. Orinoco, Con Calle Perija Edif Federacion Medica Piso 3 Of A Urb Las Mercedes.",
        code: "960",
      },
      {
        id: "WhIt3MXN18",
        city: "Caracas",
        name: "ALIADO ZOOM INVERSIONES JETES, C.A. (JETES LINIO)",
        address: "Av Orinoco Con Calle Perija Edificio Federacion Medica Piso 3 Oficina A El Cafetal",
        code: "1438",
      },
      {
        id: "WhIt3MXN19",
        city: "Caracas",
        name: "ALIADO ZOOM INVERSIONES LA GRAN FLORIDA 2304, C.A.",
        address: "Av. Juan Bautista Arismendi, Entre Calle Pedroza Y Av. Don Bosco.",
        code: "2706",
      },
      {
        id: "WhIt3MXN20",
        city: "Caracas",
        name: "ALIADO ZOOM INVERSIONES MB33, C.A.",
        address: "Avenida Del Avila, Res. Belmont, Pb, Local 01, Altamira Sur.",
        code: "651",
      },
      {
        id: "WhIt3MXN21",
        city: "Caracas",
        name: "ALIADO ZOOM INVERSIONES RRSS 1388, C.A (EL PARAISO)",
        address: "Av Jose Antonio Paez Diagonal A Plaza Wasshington Edif Hamilton Piso Pb Local 5 Urb El Paraiso.",
        code: "3062",
      },
      {
        id: "WhIt3MXN22",
        city: "Caracas",
        name: "ALIADO ZOOM LOGISTICA INTERNACIONAL VC, C.A (BARUTA)",
        address: "Avenida Ricaurte, Edificio CaÑa Dulce Local 02 Pb, Baruta.",
        code: "4035",
      },
      {
        id: "WhIt3MXN23",
        city: "Caracas",
        name: "ALIADO ZOOM MBE BELLO MONTE",
        address: "Av. Beethoven, Edif Ibaizabal, Local F, Colinas De Bello Monte.",
        code: "1192",
      },
      {
        id: "WhIt3MXN24",
        city: "Caracas",
        name: "ALIADO ZOOM MBE EL ROSAL",
        address: "Av. Venezuela Con Calle Sorocaima,torre Venezuela Diagonal A La Bolsa De Valores De Caracas, Local A, El Rosal.",
        code: "648",
      },
      {
        id: "WhIt3MXN25",
        city: "Caracas",
        name: "ALIADO ZOOM MBE LOS CORTIJOS",
        address: "Av. Francisco De Miranda, Centro Seguros La Paz, Pb, Local 19. La California.",
        code: "957",
      },
      {
        id: "WhIt3MXN26",
        city: "Caracas",
        name: "ALIADO ZOOM MBE LAS MERCEDES",
        address: "Calle Veracruz, Edificio Torreon, P.b, Local 4. Las Mercedes.",
        code: "685",
      },
      {
        id: "WhIt3MXN27",
        city: "Caracas",
        name: "ALIADO ZOOM MBE LA CASTELLANA",
        address: "1ra. Transversal De Los Palos Grandes, Entre 2da. Y 3ra. Avenida, Edificio Green Palace Planta Baja, Local 4. Los Palos Grandes.",
        code: "649",
      },
      {
        id: "WhIt3MXN28",
        city: "Caracas",
        name: "ALIADO ZOOM MBE MULTICENTRO EMPRESARIAL DEL ESTE",
        address: "Av. Francisco De Miranda Multicentro Empresarial Del Este, Planta Baja Torre Miranda. Local Pb 04, Al Lado Del Meson De Pita.",
        code: "730",
      },
      {
        id: "WhIt3MXN29",
        city: "Caracas",
        name: "ALIADO ZOOM MULTISERVICIOS BFP, C.A.",
        address: "Av. Este Nro. 2, Con Calle Sur Nro. 21, C.c. Parque Caracas, Nivel Pb, Local Nro. 36.",
        code: "2402",
      },
      {
        id: "WhIt3MXN30",
        city: "Caracas",
        name: "ALIADO ZOOM MULTISERVICIOS TEREMAR M.T. 2.012, C.A. (COCHE)",
        address: "Av Intercomunal Valle Coche C.C Coche Nivel Pb Local 25 Urb Delgado Chalbaud Diagonal Al Supermercado Supremo.",
        code: "1194",
      },
      {
        id: "WhIt3MXN31",
        city: "Caracas",
        name: "ALIADO ZOOM NETCOM CONSULTORES, C.A. (MONTALBAN CC USLAR)",
        address: "Urb. Montalban I, Av. Nro. 2, Av. Montalban I, C.c. Uslar Nivel Mirador, Local Nro. 03, La Nro. 21.",
        code: "1885",
      },
      {
        id: "WhIt3MXN32",
        city: "Caracas",
        name: "ALIADO ZOOM NETSYSTEM SOLUTIONS, C.A.",
        address: "Av. Baralt Esq El Carmen C.C. Doral Baralt Nivel 1 Local 30. Quinta Crespo.",
        code: "1108",
      },
      {
        id: "WhIt3MXN33",
        city: "Caracas",
        name: "ALIADO ZOOM ORGANIZACION MADERLING C.A.",
        address: "Av Principal CC Paseo Las Mercedes Nivel Pb Local 47, Urb. Las Mercedes.",
        code: "3039",
      },
      {
        id: "WhIt3MXN34",
        city: "Caracas",
        name: "ALIADO ZOOM PAPELERIA MIL COLORES 88 C.A (PROPATRIA)",
        address: "Av Simon Bolivar CC Propatria Nivel 1 Local A9 Urb Propatria.",
        code: "3952",
      },
      {
        id: "WhIt3MXN35",
        city: "Caracas",
        name: "ALIADO ZOOM PROPUESTAS URBANAS, C.A.",
        address: "Av. Lecuna Esquina De Miracielos Al Lado De La Estacion Del Metro Teatros. Parroquia Santa Teresa.",
        code: "1220",
      },
      {
        id: "WhIt3MXN36",
        city: "Caracas",
        name: "ALIADO ZOOM REPRESENTACIONES SIGMA 256, C.A.",
        address: "Calle Norte 2 Entre Esquina De Santa Capilla A Mijares Edif San Sebastian Piso Pb Local Nro 5 Zona Catedral.",
        code: "2435",
      },
      {
        id: "WhIt3MXN37",
        city: "Caracas",
        name: "ALIADO ZOOM REPRESENTACIONES SRV 14, C.A.",
        address: "Av. Las Palmas, Edf. Palma Alta, Torre A, Local 4, Pb.",
        code: "1625",
      },
      {
        id: "WhIt3MXN38",
        city: "Caracas",
        name: "ALIADO ZOOM SERVICIO Y ENCOMIENDAS SERVIEXPRESS PGME, C.A.",
        address: "Av Francisco De Miranda Cc Centro Lido Nivel Galeria Local G-5 Urb El Rosal.",
        code: "3922",
      },
      {
        id: "WhIt3MXN39",
        city: "Caracas",
        name: "ALIADO ZOOM SHIPNET LOS NARANJOS",
        address: "Av. El Pauji, C.C. Galerias Los Naranjos, Piso 2, Local C2-53.",
        code: "779",
      },
      {
        id: "WhIt3MXN40",
        city: "Caracas",
        name: "ALIADO ZOOM VIJAMAD GROUP, C.A.",
        address: "Av. Victoria, Edf. Meridional Pb, Entre Calle Cuba Y Av. Centro AmÉrica, Diagonal A La PanaderÍa La Flor Del Greco.",
        code: "725",
      },
      {
        id: "WhIt3MXN41",
        city: "Caracas",
        name: "ZOOM BELLO CAMPO",
        address: "Final Av. Principal De Bello Campo, Urb. Bello Campo, Qta. Grupo Zoom.",
        code: "47",
      },
      {
        id: "WhIt3MXN42",
        city: "Caracas",
        name: "ZOOM CATIA",
        address: "Av Principal De Altavista, Galpon Caracas",
        code: "3476",
      },
      {
        id: "WhIt3MXN43",
        city: "Caracas",
        name: "ZOOM CDO CATIA",
        address: "Av.ppal De Altavista, A 50 Metros De La Textileria Ovejita, Galpon Grupo Zoom.",
        code: "48",
      },
      {
        id: "WhIt3MXN44",
        city: "Caracas",
        name: "ZOOM CHACAITO I",
        address: "Av. Tamanaco, Urbanizacion El Rosal, Centro Comercial Arta, Piso 1, Local 1-3.",
        code: "825",
      },
      {
        id: "WhIt3MXN45",
        city: "Caracas",
        name: "ZOOM LA CALIFORNIA",
        address: "Av Francisco De Miranda, Residencias MÓnaco Local B, Urb La California Norte.",
        code: "1257",
      },
      {
        id: "WhIt3MXN46",
        city: "Caracas",
        name: "ZOOM LA URBINA",
        address: "Sector Sur, Calle 7, Urb La Urbina, Edificio Grupo Zoom.",
        code: "46",
      },
      {
        id: "WhIt3MXN47",
        city: "Caracas",
        name: "ZOOM MAKRO LA YAGUARA",
        address: "Av. Intercomunal De Antimano Cruce Con Av. Principal De La Yaguara.",
        code: "1372",
      },
      {
        id: "WhIt3MXN48",
        city: "Caracas",
        name: "ZOOM PARQUE HUMBOLDT",
        address: "Centro Comercial Parque Humboldt, Local 10, Urb. Prados Del Este.",
        code: "1214",
      },
      {
        id: "WhIt3MXN49",
        city: "Caracas",
        name: "ZOOM SAN MARTIN",
        address: "Av. San Martin, Entre La 2da Y 3era Calle Los Molinos, Urb. Los Molinos, Edificio Komplot, Pb. P.ref. Edificio Komplot, Pb.",
        code: "50",
      },



    ]
  },
  {
    name: "Falcón",
    agencies: [
      {
        id: "lufaqFPrS1",
        city: "Coro",
        name: "ALIADO ZOOM ANCELL, C.A.",
        address: "Av Manaure Con Calle El Sol Cc San Antonio Plaza P.b Local 08.",
        code: "3953",
      },
      {
        id: "lufaqFPrS2",
        city: "Coro",
        name: "ALIADO ZOOM INVERSIONES TU PUNTO EXPRESS, C.A",
        address: "Calle Falcon Cc Ferial Nivel Pb Local 01, Zona Centro Santa Ana.",
        code: "3995",
      },
      {
        id: "lufaqFPrS3",
        city: "Coro",
        name: "ZOOM CORO",
        address: "Sector Los Tres Platos, Av. Los Medanos Cruce Con Av. Independencia, Edificio Aref, Pb., Local 1.",
        code: "59",
      },
      {
        id: "lufaqFPrS4",
        city: "Dabajuro",
        name: "ALIADO ZOOM INVERSIONES ARDILA LOPEZ, C.A.",
        address: "Av Bolivar Local Nro S/n Sector El Cerro Debajuro.",
        code: "3540",
      },
      {
        id: "lufaqFPrS5",
        city: "Punto Fijo",
        name: "ALIADO ZOOM FCG 26, C.A.",
        address: "Garces Entre Calles Argentina Y Paraguay, Los Cardones Piso Pb Local 1 Centro De Punto Fijo.",
        code: "1799",
      },
      {
        id: "lufaqFPrS6",
        city: "Punto Fijo",
        name: "ALIADO ZOOM MBE PARAGUANA",
        address: "Av. Pumarrosa, Edificio Maria Luisa, Numero 61-16, Local 2, Urbanizacion Santa Fe.",
        code: "709",
      },
      {
        id: "lufaqFPrS7",
        city: "Punto Fijo",
        name: "ALIADO ZOOM PACKAGE DELIVERY PARAGUANA BY Z&Z, C.A.",
        address: "Av Las Virtudes Cc Las Virtudes Nivel Pb Local Aem20, Sector Maraven Punta Cardon.",
        code: "4039",
      },
      {
        id: "lufaqFPrS8",
        city: "Punto Fijo",
        name: "ALIADO ZOOM TRADE EXPRESS, C.A.",
        address: "Urb. Puerta Maraven, Av. Ollarvides, Local Nro. 264.",
        code: "1688",
      },
      {
        id: "lufaqFPrS9",
        city: "Punto Fijo",
        name: "ZOOM PUNTO FIJO",
        address: "Sector Centro, Calle Arismendi, Entre Talavera Y Las Palmas, Local 203.",
        code: "110",
      },
    ]
  },
  {
    name: "Guárico",
    agencies: [
      {
        id: "HaByAAwwq1",
        city: "Altagracia De Orituco",
        name: "ALIADO ZOOM INVERSIONES C.S.M., C.A.",
        address: "Calle Hurtado Ascanio Local Nro 03. Sector El Cumbito.",
        code: "1636",
      },
      {
        id: "HaByAAwwq2",
        city: "Calabozo",
        name: "ALIADO ZOOM CASA DEL NYLON M.S C.A.",
        address: "Cr 11 Entre Calles 8 Y 9 Edif Germary Piso P/b Local S/n Sector Casco Central.",
        code: "3924",
      },
      {
        id: "HaByAAwwq3",
        city: "Calabozo",
        name: "ALIADO ZOOM M L CENTER, C.A.",
        address: "Sector Centro Calabozo, Crrt. N°. 11, Entre Calles N°. 6 Y 7, Edf. Caryubel, Piso Pb, Local N°. 01.",
        code: "2394",
      },
      {
        id: "HaByAAwwq4",
        city: "Calabozo",
        name: "ZOOM CALABOZO",
        address: "Calle 5 Entre Carreras 9 Y 10, Edificio Villavicencio, P.b Locales 5 Y 6. P.ref. A 50 Mts Del Museo De Calabozo.",
        code: "872",
      },
      {
        id: "HaByAAwwq5",
        city: "El Sombrero",
        name: "ALIADO ZOOM INVERSIONES MOTO REPUESTOS EL SOMBRERO, C.A.",
        address: "Calle Fraternidad Cruce Con Calle Los Estudiantes Local Nro S/n, Sector Frente A La Plaza Bolivar El Sombrero.",
        code: "2982",
      },
      {
        id: "HaByAAwwq6",
        city: "San Juan De Los Morros",
        name: "ALIADO ZOOM INVERSIONES YEDAEVE, C.A.",
        address: "Sector Pueblo Nuevo, Av. Bolivar Cruce Con 1ro De Mayo Nro. 41-d.",
        code: "2590",
      },
      {
        id: "HaByAAwwq7",
        city: "San Juan De Los Morros",
        name: "ZOOM SAN JUAN DE LOS MORROS",
        address: "Final Av. Roscio, Res. Femel Pb. Local B.",
        code: "945",
      },
      {
        id: "HaByAAwwq8",
        city: "Valle De La Pascua",
        name: "ZOOM VALLE DE LA PASCUA",
        address: "Calle Bolivar Entre Calles Atarraya Y Gonzalez Padron, P.ref. Fte. A Las Oficinas De Filigas.",
        code: "889",
      },
    ]
  },
  {
    name: "La Guaira",
    agencies: [
      {
        id: "SKtX5z6k91",
        city: "Caraballeda",
        name: "ALIADO ZOOM INVERSIONES LA COSTANERA 1725, C.A.",
        address: "Av. La Costanera Con Copacabana, C.C. Margarita, Nivel S/n, Local S/n, Urb. Palmar Este.",
        code: "1451",
      },
      {
        id: "SKtX5z6k92",
        city: "Caraballeda",
        name: "ALIADO ZOOM MULTISERVICIOS DHAMAR C.A.",
        address: "Urb. Caribe. Caraballera. Av Boulevard Naiguata, Edf. Residencia, Gran Terraza. Piso Pb. Local Nro. 1-4.",
        code: "3114",
      },
      {
        id: "SKtX5z6k93",
        city: "Catia La Mar",
        name: "ALIADO ZOOM INVERSIONES CARIBE PHONE M.K, C.A.",
        address: "Calla Tacagua, Calle 14 Cc Oceano Piso 1 Nivel 1 Local 10 Urb Atlantida.",
        code: "3967",
      },
      {
        id: "SKtX5z6k94",
        city: "Catia La Mar",
        name: "ZOOM CATIA LA MAR",
        address: "Av. Atlantida, Calles 5 Y 6, Qta. Hucarimar, Pb. Local 1.",
        code: "74",
      },
      {
        id: "SKtX5z6k95",
        city: "Maiquetía",
        name: "ALIADO ZOOM CORPORACION KAIROS C.A.",
        address: "Calle Los Pipotes Entre La Esquina Del Brillante Y Los Pipotes Casa Nro 129 Nivel P.b.",
        code: "3917",
      },
      {
        id: "SKtX5z6k96",
        city: "Maiquetía",
        name: "ALIADO ZOOM INVERSIONES R.C. 2014, C.A.",
        address: "Av Soublette Cc Litoral Nivel Uno Local 14 Y 15 Sector Maiquetia Vargas.",
        code: "1586",
      },
    ]
  },
  {
    name: "Lara",
    agencies: [
      {
        id: "wkN9e9seG1",
        city: "Barquisimeto",
        name: "ALIADO ZOOM CONSTRUCTORA CUATRO ENE, C.A.",
        address: "Av. Lara Con Av. Los Leones, Ctro. Comercial Parque Real, Nivel 1, Local 10.",
        code: "306",
      },
      {
        id: "wkN9e9seG2",
        city: "Barquisimeto",
        name: "ALIADO ZOOM ETESCA, C.A.",
        address: "Carrera 25, Entre Calle 40 Y 41 Nro 2.",
        code: "1069",
      },
      {
        id: "wkN9e9seG3",
        city: "Barquisimeto",
        name: "ALIADO ZOOM FREYCA 2009, C.A.",
        address: "Calle 14 Entre Carreras 18 Y 19 Qta Nelly Local Nro 3",
        code: "956",
      },
      {
        id: "wkN9e9seG4",
        city: "Barquisimeto",
        name: "ALIADO ZOOM MBE BARQUISIMETO",
        address: "Av. Venezuela, Entre Av. Bracamonte Y Av. Los Leones, Centro Comercial Imeca, Piso 1, Local 1-h Y 1-g.",
        code: "703",
      },
      {
        id: "wkN9e9seG5",
        city: "Barquisimeto",
        name: "ALIADO ZOOM MBE ZONA INDUSTRIAL",
        address: "Av. Las Industrias, Edif. Sede De Industriales Del Estado Lara, Urb. Rafael Caldera",
        code: "964",
      },
      {
        id: "wkN9e9seG6",
        city: "Barquisimeto",
        name: "ALIADO ZOOM PRINT SOLUTIONS, C.A.",
        address: "Av. Madrid, Urb. El Parque, C.c. Alfa, Nivel P/b, Local 6.",
        code: "1520",
      },
      {
        id: "wkN9e9seG7",
        city: "Barquisimeto",
        name: "ALIADO ZOOM RR INVERSIONES TECNOLOGICAS, C.A.",
        address: "Carrera 19 Con Calles 33 Y 34 # 33-68, Barquisimeto.",
        code: "1695",
      },
      {
        id: "wkN9e9seG8",
        city: "Barquisimeto",
        name: "ALIADO ZOOM TRANSPORTE FORTALEZA, C.A.",
        address: "Carrera 23, Entre Calles 52 Y 54, Urbanizacion Santa Eduvigis,conjunto Residencial Lara Palace, Nro. 1-06.",
        code: "1669",
      },
      {
        id: "wkN9e9seG9",
        city: "Barquisimeto",
        name: "ZOOM AEROPUERTO JACINTO LARA",
        address: "Av. Vicente Landaeta Gil Con Av. La Salle, Aeropuerto General Jacinto Lara P.b.",
        code: "612",
      },
      {
        id: "wkN9e9se10",
        city: "Barquisimeto",
        name: "ZOOM BARQUISIMETO",
        address: "Carrera 24, Entre Calles 23 Y 24, Nro. 23-69. P.ref. Frente A La Plaza Mora, Diagonal Al Iutirla.",
        code: "15",
      },
      {
        id: "wkN9e9se11",
        city: "Barquisimeto",
        name: "ZOOM FIN DE SIGLO BARQUISIMETO",
        address: "Calle 20, Entre Carreras 31 Y 32, Edf. Fin De Siglo Piso 2. P.ref. Detras Del Centro Comercial Arca.",
        code: "149",
      },
      {
        id: "wkN9e9se12",
        city: "Cabudare",
        name: "ALIADO ZOOM INVERSIONES GRATECA 2014, C.A.",
        address: "Av. La Montanita C.c.almarriera Planta Baja Alta. Local L-29. Urb.almarriera. Los Rastrojos.cabudare.",
        code: "2489",
      },
      {
        id: "wkN9e9se13",
        city: "Cabudare",
        name: "ZOOM CABUDARE",
        address: "Avenida Libertador Entre Calles Miguel Bernal Y Juarez, Centro Comercial Libertador, Locales Pb-02 Y Pb-03.",
        code: "873",
      },
      {
        id: "wkN9e9se14",
        city: "Carora",
        name: "ALIADO ZOOM PINTURAS CARORA, C.A",
        address: "Av Fco De Miranda E/calle Lisbos Y Coromoto Local Tiendas Montana, Sector Fco De Miranda.",
        code: "4057",
      },
      {
        id: "wkN9e9se15",
        city: "El Tocuyo",
        name: "ALIADO ZOOM DISTRIBUIDORA DEL SUR 83, C.A.",
        address: "Calle 20 Entre 7 Y 8 Cruce Final Avenida Fraternidad Urb Corpahuaico.",
        code: "1668",
      },
    ]
  },
  {
    name: "Miranda",
    agencies: [
      {
        id: "UTu3X35Ih1",
        city: "Charallave",
        name: "ZOOM CHARALLAVE CIUDAD CONCORDIA",
        address: "Av. Tosta Garcia, Centro Comercial Ciudad Concordia, Piso Nro. 1, Locales 8, 9 Y 10.",
        code: "54",
      },
      {
        id: "UTu3X35Ih2",
        city: "Cua",
        name: "ALIADO ZOOM COMERCIAL NOFA C.A",
        address: "Calle Jose Maria Carreño Local Minicozzi Nro Pb Sector Casco Central Cua.",
        code: "3312",
      },
      {
        id: "UTu3X35Ih3",
        city: "Guarenas",
        name: "ALIADO ZOOM ESTACIONAMIENTO Y MULTISERVICIOS SOUTO C.a",
        address: "Urb. Nro 27 De Febrero,ctra Nacional, Local Estacionamiento Y Multiservicios Souto Nro. S/n.",
        code: "2945",
      },
      {
        id: "UTu3X35Ih4",
        city: "Guarenas",
        name: "ZOOM C.C MIRANDA",
        address: "Av. Intercomunal Menca De Leoni, C.c. Miranda, Local 30-22. P.ref. Area De Minitiendas, Parte Alta De Guarenas.",
        code: "163",
      },
      {
        id: "UTu3X35Ih5",
        city: "Guarenas",
        name: "ZOOM GUARENAS",
        address: "Zona Industrial Santa Cruz, Urb. Los Naranjos, P.ref. Pasando Los Bomberos Entrando Por La Levis Al Lado De Pandok.",
        code: "67",
      },
      {
        id: "UTu3X35Ih6",
        city: "Guatire",
        name: "ALIADO ZOOM INVERSIONES HERSIL, C.A.",
        address: "Av Principal CC Castillejo Nivel 1 Local 02-14 Urb Castillejo.",
        code: "4033",
      },
      {
        id: "UTu3X35Ih7",
        city: "Guatire",
        name: "ZOOM C.C. BUENAVENTURA VISTA PLACE",
        address: "Av. Intercomunal Guarenas-guatire, Centro Comercial Buenaventura Vista Place Nivel Plaza Locales Pl-94 Y Pl-95.",
        code: "1452",
      },
      {
        id: "UTu3X35I20",
        city: "Higuerote",
        name: "ALIADO ZOOM TLR 1148 VIAJES Y TURISMO, C.A.",
        address: "Sector Tocoron Higuerote, Av. Andres Bello Eloy Blanco, C.C. Anjulicar Nivel Pb, Local Nro. 3.",
        code: "1886",
      },
      {
        id: "UTu3X35Ih8",
        city: "Los Teques",
        name: "ALIADO ZOOM CENTRO DE SERVICIOS MIRANDA 2705, C.A (SUC. LOS TEQUES)",
        address: "Calle Miranda Con Guaicaipuro Norte Mini Centro Comercial Oriente, Sector 4 Esquinas.",
        code: "4053",
      },
      {
        id: "UTu3X35Ih9",
        city: "Los Teques",
        name: "ZOOM LOS TEQUES",
        address: "Sector El Tambor, Av. Pedro Ruffo Ferrer, C.C. Los Teques Local A5. P.ref. Frente Al Banco De Venezuela.",
        code: "73",
      },
      {
        id: "UTu3X35I10",
        city: "San Antonio De Los Altos",
        name: "ALIADO ZOOM CENTRO DE SERVICIOS MIRANDA 2705, C.A.",
        address: "Carretera Panamericana, Km 15 Edif Ferretotal Piso Pb, Ofc 1-a, Sector Las Minas, Al Lado Del Mc Donald, San Antonio De Los Altos, Estado Miranda.",
        code: "1197",
      },
      {
        id: "UTu3X35I11",
        city: "San Antonio De Los Altos",
        name: "ALIADO ZOOM ENVIOS LOS SALIAS, C.A.",
        address: "Carretera Panamericana Km 16 Bajando Por El Distribuidor De La Rosaleda (sentido Caracas) A Mano Derecha 100 Mts Antes Del C.C. La Casona I, Local Zoom.",
        code: "1020",
      },
      {
        id: "UTu3X35I12",
        city: "Santa Teresa Del Tuy",
        name: "ALIADO ZOOM CENTRO DE CONEXIONES SOFI-K, C.A.",
        address: "Calle Sucre Con Av. Ayacucho, Local C. Nro. 3.",
        code: "1247",
      },

    ]
  },
  {
    name: "Monagas",
    agencies: [
      {
        id: "7cVrjKw6Ss",
        city: "Maturín",
        name: "ALIADO ZOOM ELARBA",
        address: "Avenida Bolivar, Edificio Elarba, Piso Pb, Local 133, Sector Centro De Maturín.",
        code: "3417",
      },
      {
        id: "RdHH1JyDZo",
        city: "Maturín",
        name: "ALIADO ZOOM GRUPO FERRECOLOR, C.A.",
        address: "Av. Raul Leoni Cruce Con Prolongacion Boyaca, Edf. Nar-oly, Torre A, P. Pb, Local A Sur, Sector Centro.",
        code: "1830",
      },
      {
        id: "PvBKa1V8Ej",
        city: "Maturín",
        name: "ALIADO ZOOM MBE MATURIN",
        address: "Av. Alirio Ugarte Pelayo, Edificio Vespa, Local 6, Sector Bajo Guarapiche.",
        code: "696",
      },
      {
        id: "qqtMWgZSXC",
        city: "Maturín",
        name: "ALIADO ZOOM MULTISERVICIOS HERSO, C.A.",
        address: "Calle Principal, Centro Comercial Los Samanes, Local 1, Planta Baja, Sector Los Samanes.",
        code: "1580",
      },
      {
        id: "zABfdB9OCA",
        city: "Maturín",
        name: "ALIADO ZOOM NEXUS VENEZUELA, C.A",
        address: "Av. Azcue Con Av Rojas Sector Centro, Local Nro. 114 A Dos Cuadras De La Av. Bolivar.",
        code: "2343",
      },
      {
        id: "89MMkF6PWy",
        city: "Maturín",
        name: "ALIADO ZOOM SMART SYSTEM 0291, C.A",
        address: "Av Alirio Ugarte Pelayo Cc Monagas Plaza Nivel P.b Local 65 Sector Boqueron.",
        code: "3538",
      },
      {
        id: "oXM7i9n4eo",
        city: "Maturín",
        name: "ZOOM MATURIN",
        address: "Av Libertador Cruce Con Avenida Ejercito Local Zoom Sector Fundemos.",
        code: "89",
      },
      {
        id: "he6bnGaZWW",
        city: "Punta De Mata",
        name: "ALIADO ZOOM PAPELERIA MACHI, C.A",
        address: "Ctra Punta De Mata Maturin, Ramal 7 Con Calle 4 Local Nro S/n Urb Raul Leoni.",
        code: "1581",
      },
    ]
  },
  {
    name: "Mérida",
    agencies: [
      {
        id: "vSd5xsnDG1",
        city: "Bailadores",
        name: "WALDO SHOP C.A.",
        address: "Local 1 Centro Comercial El Pentágono, Ubicado En La Calle 8 Entre 3 Y 4 De La Ciudad De Bailadores Estado Mérida.",
        code: "3925",
      },
      {
        id: "vSd5xsnDG2",
        city: "Caja Seca",
        name: "ALIADO ZOOM GUZSI 2022, C.A.",
        address: "Calle Lateral Frente A La Salida Del Terminal De Pasajeros Local Nro 15, Sector Caja Seca.",
        code: "4054",
      },
      {
        id: "vSd5xsnDG4",
        city: "Ejido",
        name: "ALIADO ZOOM BUFECORP COMPAÑIA ANONIMA",
        address: "Calle Sucre Frente A La Plaza Bolivar De Ejido Con Av Bolivar C.c Ejido Pb Local 1-c.",
        code: "3749",
      },
      {
        id: "vSd5xsnDG5",
        city: "El Vigia",
        name: "ZOOM EL VIGIA",
        address: "Av. 3 Nro 3-88, Barrio Panamericano, Entre Av. Bolivar Y Don Pepe Rojas, P.ref. Diagonal Al Distribuidor Carrero Mendez.",
        code: "745",
      },
      {
        id: "vSd5xsnDG6",
        city: "Lagunillas",
        name: "ALIADO ZOOM DADOS M&L EXPRESS, C.A.",
        address: "Calle 7 Diagonal Al Terminal Cc Selma Plaza Nivel P.b Local 01",
        code: "4034",
      },
      {
        id: "vSd5xsnDG7",
        city: "Mérida",
        name: "ALIADO ZOOM BOOCH, COMPAÑIA ANONIMA, C.A.",
        address: "Av 3 Independencia Esquina Calle 21 Laso Cc La Rosalera Nivel 03 Of 01 Sector Centro Merida.",
        code: "3151",
      },
      {
        id: "vSd5xsnDG8",
        city: "Mérida",
        name: "ALIADO ZOOM INVERSIONES TERVAS, C.A.",
        address: "Sector La Parroquia, Calle Paez, C.c. La Candelaria, Nivel Pb., Local 01-a.",
        code: "1797",
      },
      {
        id: "vSd5xsnDG9",
        city: "Mérida",
        name: "ALIADO ZOOM JHALMAR.COM, C.A.",
        address: "Av Los Proceres Edif Longimar Piso Pb Local 2 Y 3, Sector Aldea Santa Barbara.",
        code: "4059",
      },
      {
        id: "vSd5xsnD10",
        city: "Mérida",
        name: "ALIADO ZOOM LA FERMATA DEL GIORNO C.A.",
        address: "Av. Las Americas Edif. Hipermercado, Garzon Piso Planta Baja. Local 1-4, Sector Santa Barbara.",
        code: "3148",
      },
      {
        id: "vSd5xsnD11",
        city: "Mérida",
        name: "ALIADO ZOOM SERVIPOST, C.A.",
        address: "Av. Miranda, Centro Comercial Doña Heraclita Local 2.",
        code: "382",
      },
      {
        id: "vSd5xsnD12",
        city: "Mérida",
        name: "ALIADO ZOOM TELANGA SERVICIOS, C.A.",
        address: "Sector Los Sauzales, Av. Las Americas, Centro Comercial Mercado Murachi, Nivel Unico Local 44.",
        code: "1475",
      },
      {
        id: "vSd5xsnD13",
        city: "Mérida",
        name: "ZOOM MERIDA",
        address: "Av. Don Tulio Febres Cordero, Edf. Don Miguel, Pb. Local 37-94.",
        code: "95",
      },
      {
        id: "vSd5xsnD14",
        city: "Tovar",
        name: "ALIADO ZOOM COMERCIALIZADORA GLOBALES DE VENEZUELA, C.A.",
        address: "Av Cristobal Mendoza Edif Echeverria Piso 1 Local 3 Y 4.",
        code: "4017",
      },
      {
        id: "vSd5xsnD15",
        city: "Tovar",
        name: "ALIADO ZOOM FELDORS, C.A.",
        address: "Sector El Arado, Calle Nro. 9, C.c. Unicentro Los Angeles, Nivel Pb., Local Nro. 4.",
        code: "1750",
      },
    ]
  },
  {
    name: "Nueva Esparta",
    agencies: [
      {
        id: "tQSV0EZat1",
        city: "Juan Griego",
        name: "ALIADO ZOOM DISTRIBUIDORA MIMISIMA",
        address: "C.C. La Estancia, Local L23, Juan Griego.",
        code: "1702",
      },
      {
        id: "tQSV0EZat2",
        city: "Pampatar",
        name: "ALIADO ZOOM MAR EXPRESS 2004, C.A. RATTAN PLAZA",
        address: "Av Aldonza Manrique Con Av Jovito Villalva C.C Rattan Plaza Nivel Pb Local P-07a Sector Playa El Angel Pampatar.",
        code: "1527",
      },
      {
        id: "tQSV0EZat3",
        city: "Pampatar",
        name: "ALIADO ZOOM XIJAP, C.A. LOS ROBLES",
        address: "	Av Jovito Villalba C.C. Centro Artesanal Los Robles Nivel P.b.",
        code: "1555",
      },
      {
        id: "tQSV0EZat4",
        city: "Porlamar",
        name: "ALIADO ZOOM AFFARI BOOM, C.A.",
        address: "Av. Llano Adentro C.C El Mercado La Isla Nivel 1,local L-411,sector Llano Adentro.",
        code: "1811",
      },
      {
        id: "tQSV0EZat5",
        city: "Porlamar",
        name: "ALIADO ZOOM ENCOMIENDAS ISLA 2004, C.A. (CALLE CAMPOS)",
        address: "Calle Campos Edificio Juamo Pb.",
        code: "1554",
      },
      {
        id: "tQSV0EZat6",
        city: "Porlamar",
        name: "ALIADO ZOOM MBE MARGARITA",
        address: "Av Paseo Cultural Ramon Vasquez Brito Cc Boulevard Porlamar Edificio S Nivel 1 Local S-3a Sector 4 De Mayo.",
        code: "1488",
      },
      {
        id: "tQSV0EZat7",
        city: "Porlamar",
        name: "ZOOM PORLAMAR",
        address: "Av. 4 De Mayo, Residencias Panerco, Planta Baja, Local 1.",
        code: "99",
      },
      {
        id: "tQSV0EZat8",
        city: "Porlamar",
        name: "ZOOM PORLAMAR CENTRO",
        address: "Calle VelÁsquez Con Calle DÍaz, Centro Comercial Concord, Local #100. Pasillo Central.",
        code: "235",
      },
    ]
  },
  {
    name: "Portuguesa",
    agencies: [
      {
        id: "ukHw8Ya7v1",
        city: "Acarigua",
        name: "ALIADO ZOOM AG SERVICIOS, C.A.",
        address: "Sector Redoma De Araure, Av. Municipalidad, Centro Comercial Buenaventura, Nivel Agricola, Local A-19.",
        code: "1215",
      },
      {
        id: "ukHw8Ya7v2",
        city: "Acarigua",
        name: "ALIADO ZOOM GLOBAL EXPRESS, C.A.",
        address: "Av. Libertador, E/ Calles 32 Y 33 C.c. Sol De Curpa Nivel Pb., Local 7.",
        code: "2252",
      },
      {
        id: "ukHw8Ya7v3",
        city: "Acarigua",
        name: "ZOOM ACARIGUA",
        address: "Calle 30 Con Av. 35, Centro Comercial PÁez, Planta Baja, Local 02.",
        code: "2",
      },
      {
        id: "ukHw8Ya7v4",
        city: "Guanare",
        name: "ZOOM GUANARE",
        address: "Av. Simon Bolivar Entre Av. Unda Y Calle 9, Centro Comercial Autocentro, Pb. Local Zoom.",
        code: "875",
      },
      {
        id: "ukHw8Ya7v5",
        city: "Turen",
        name: "ALIADO ZOOM VIAGROCEL, C.A.",
        address: "Av. Ricardo Perez Zambrano, Edif. Agosi. Local Nro. 1. Villa Bruzual.",
        code: "274",
      },
    ]
  },
  {
    name: "Sucre",
    agencies: [
      {
        id: "VDoyTvnDb1",
        city: "Carúpano",
        name: "ZOOM CARUPANO",
        address: "Av. Libertador Con Calle Monagas, Edf. Turbo Oriente, P. Pb., Parroquia Santa Catalina, Municipio Bermudez.",
        code: "744",
      },
      {
        id: "VDoyTvnDb2",
        city: "Cumaná",
        name: "ALIADO ZOOM DESTINY EXPRESS H.F.R, C.A.",
        address: "Av Humboldt CC San Onofre Nivel Pb Local Nro 13, Sector Santa Catalina.",
        code: "4055",
      },
      {
        id: "VDoyTvnDb3",
        city: "Cumaná",
        name: "ALIADO ZOOM FLEVIMAR, C.A.",
        address: "Sector Santa Rosa, Av. Santa Rosa, C.c. Santa Rosa, Nivel Pb., Local 06,",
        code: "2177",
      },
      {
        id: "VDoyTvnDb4",
        city: "Cumaná",
        name: "ALIADO ZOOM MBE CUMANA",
        address: "Av.cristobal Colon Perimetal, Sec. El Diqui, C.C. Marina Plaza, Edif. D-3, Local P.b.-4.",
        code: "1115",
      },
      {
        id: "VDoyTvnDb5",
        city: "Cumaná",
        name: "ZOOM CUMANA",
        address: "Calle Mariño, Edf. San Ignacio Pb., Local 1. P.ref. Frente Al C.C. Cumana Plaza.",
        code: "60",
      },
    ]
  },
  {
    name: "Trujillo",
    agencies: [
      {
        id: "trncWIwaC1",
        city: "Boconó",
        name: "ALIADO ZOOM INVERSIONES MUNDO ELECTRONIC BOCONO, C.A.",
        address: "Sector Centro, Av. Carabobo Entre Calle Monsenor Jauregui Y Andres Bello, Casa Nro. 6-22.",
        code: "1755",
      },
      {
        id: "trncWIwaC2",
        city: "Valera",
        name: "ZOOM VALERA",
        address: "Avenida BolÍvar Edificio Galotta Ii, Urb Las Acacias Al Lado De La Bera.",
        code: "139",
      },
    ]
  },
  {
    name: "Táchira",
    agencies: [
      {
        id: "HVioZ9xfN1",
        city: "Colón",
        name: "ALIADO ZOOM CONEEXPRESS, C.A. (COLON)",
        address: "Sector Centro Colon Tachira,ctra Nro. 7, Con Calle Nro. 3, Casa Nro. 6-81.",
        code: "1898",
      },
      {
        id: "HVioZ9xfN2",
        city: "Coloncito",
        name: "ALIADO ZOOM OCCIDENTAL DE TRANSPORTE, C.A.",
        address: "Sector Casco Central Coloncito, Cr. Nro. 04, Casa Nro. 3-47.",
        code: "2587",
      },
      {
        id: "HVioZ9xfN3",
        city: "El Piñal",
        name: "ALIADO ZOOM INVERSIONES MAREXPRESS 83, C.A.",
        address: "Sector El Piñal, Calle N°. 1 Entre Carrera N°. 3 Y 4, Casa N°. 3-19. (san Rafael Del Piñal).",
        code: "2703",
      },
      {
        id: "HVioZ9xfN4",
        city: "La Fría",
        name: "ALIADO ZOOM CENTRO DE CONEXIONES LA FRIA, C.A.",
        address: "Sector Terminal De Pasajeros La Fria, Calle 2 Entre Carreras 18 Y 19, Local Nro. 25.",
        code: "1723",
      },
      {
        id: "HVioZ9xfN5",
        city: "La Grita",
        name: "ALIADO ZOOM INVERSIONES CHICHO S COMPUTERS C.A.",
        address: "Calle 2 Entre Carreras 11 Y 12 Casa 11-86 Sector Casco Central.",
        code: "3654",
      },
      {
        id: "HVioZ9xfN6",
        city: "Palmira",
        name: "ALIADO ZOOM SERVI SUMINISTRO YIREC, C.A.",
        address: "Sector Palmira, Carretera 5, Local Nro. 2.",
        code: "1757",
      },
      {
        id: "HVioZ9xfN7",
        city: "Rubio",
        name: "ALIADO ZOOM INVERSIONES Y CREACIONES GASU, C.A.",
        address: "Calle 14 Entre Av. 8 Y 9, Centro Comercial Dona Ivonne, P.b. Local 6 Y 7.",
        code: "1104",
      },

      {
        id: "HVioZ9xfN8",
        city: "San Antonio Del Táchira",
        name: "ALIADO ZOOM TRANSPORTE MARVAL C.A.",
        address: "Av Venezuela Carrera 6 Local Nro 6-02,sector Bolivar.",
        code: "3562",
      },
      {
        id: "HVioZ9xfN9",
        city: "San Antonio Del Táchira",
        name: "ZOOM SAN ANTONIO",
        address: "Calle 9 Entre Carreras 10 Y 11 Número 10-44 Barrio La Popa San Antonio Del Táchira.",
        code: "112",
      },
      {
        id: "HVioZ9xf10",
        city: "San Cristóbal",
        name: "ALIADO ZOOM AVY C.A.",
        address: "Vda 8 Y 9 Casa Nro 2-24 Sector Prolongacion De La Unidad Vecinal.",
        code: "3149",
      },
      {
        id: "HVioZ9xf11",
        city: "San Cristóbal",
        name: "ALIADO ZOOM EDUARKAR, C.A.",
        address: "Av. Ferrero Tamayo, Cruce Av. Las Pilas Centro Comercial Barata, Local P.b-03.",
        code: "1163",
      },
      {
        id: "HVioZ9xf12",
        city: "San Cristóbal",
        name: "ALIADO ZOOM ENSALUD FARMACIA EL TAMA C.A.",
        address: "Calle 3 Esquina F Cc Los Andes Nivel Pb Local 15 Y 16 Zona Industrial Paramillo.",
        code: "3464",
      },
      {
        id: "HVioZ9xf13",
        city: "San Cristóbal",
        name: "ALIADO ZOOM EXPRESS INTERNACIONAL, C.A.",
        address: "Cr 19 Entre Calle 15 Y 16 Local Nro 15-15, Barrio Obrero.",
        code: "4060",
      },
      {
        id: "HVioZ9xf14",
        city: "San Cristóbal",
        name: "ALIADO ZOOM GACELA EXPRESS, C.A. (SAN CRISTOBAL)",
        address: "Calle 2 Nro 10-45 Barrio El Carmen La Concordia.",
        code: "1225",
      },
      {
        id: "HVioZ9xf15",
        city: "San Cristóbal",
        name: "ALIADO ZOOM GRIMALKA EXPRESS, C.A.",
        address: "Av. 5ta. Entre Calles Nro. 3 Y 4,edf. A.c., Piso Pb, Local Nro. 8,sector Centro.",
        code: "2399",
      },
      {
        id: "HVioZ9xf16",
        city: "San Cristóbal",
        name: "ALIADO ZOOM INVERAPIDO, C.A.",
        address: "Calle 12, Entre Carrera 4 Y 5ta Avenida Nro 4-35 La Ermita ( Tapon Lacor) San Cristobal.",
        code: "1121",
      },
      {
        id: "HVioZ9xf17",
        city: "San Cristóbal",
        name: "ALIADO ZOOM MBE SAN CRISTOBAL",
        address: "Calle 15 Con Carrera 22, Edif. Apolo, Local 3, Barrio Obrero.",
        code: "780",
      },
      {
        id: "HVioZ9xf18",
        city: "San Cristóbal",
        name: "ALIADO ZOOM VIRTUAL OFFICE.NET, C.A. (LA CONCORDIA)",
        address: "Av 19 De Abril Nro 9-29 Entre Carreras 9 Y 10 La Concordia.",
        code: "764",
      },
      {
        id: "HVioZ9xf19",
        city: "San Cristóbal",
        name: "ZOOM CDO SVZ",
        address: "Calle 14 Con Callejuela La Republica, Nro G-46. Sector Puente Real.",
        code: "1204",
      },
      {
        id: "HVioZ9xf20",
        city: "San Cristóbal",
        name: "ZOOM MULTISERVICIOS BARRIO OBRERO",
        address: "Calle 11 Entre Carreras 18 Y 19 Nro 19-59, Calle 11 Entre Carreras 18 Y 19 Nro 19-59.",
        code: "1280",
      },
      {
        id: "HVioZ9xf21",
        city: "San Cristóbal",
        name: "ZOOM SAN CRISTOBAL",
        address: "Av. Libertador, Edificio El Maracucho Pb. Local A-56. P.ref. Frente Al Hotel Hamburgo.",
        code: "117",
      },
      {
        id: "HVioZ9xf22",
        city: "Urena",
        name: "ALIADO ZOOM GACELA EXPRESS, C.A. (UREÑA)",
        address: "Calle 5, Barrio La Goajira, Carretera 5, Local 01.",
        code: "914",
      },
    ]
  },
  {
    name: "Yaracuy",
    agencies: [
      {
        id: "5gSRwm2uf1",
        city: "San Felipe",
        name: "ZOOM SAN FELIPE",
        address: "Av. La Patria Con Av. 19 De Abril, Centro Comercial Aracoi, Local C-5. P.ref. Fte. A Oficinas De Caley.",
        code: "874",
      },
      {
        id: "5gSRwm2uf2",
        city: "Yaritagua",
        name: "ALIADO ZOOM LA BOUTIQUE DEL CELULAR YARITAGUA, C.A.",
        address: "Av. Padre Torres. Calle 19 Entre Carretera 11 Y 12.",
        code: "308",
      },
    ]
  },
  {
    name: "Zulia",
    agencies: [
      {
        id: "aA0zBlRXr1",
        city: "Cabimas",
        name: "ALIADO ZOOM ROMARCA INTERNACIONAL VENEZUELA C.A.",
        address: "Av Intercomunal Edif Hotel Di Maio Piso Pb Local 1 Sector El Dividive.",
        code: "3478",
      },
      {
        id: "aA0zBlRXr2",
        city: "Ciudad Ojeda",
        name: "ALIADO ZOOM KAISER EXPRESS, C.A.",
        address: "Calle Vargas Con Calle Campo Elias Cc Nocciano Nivel Pb Local 2 Sector Casco Central.",
        code: "3895",
      },
      {
        id: "aA0zBlRXr3",
        city: "Ciudad Ojeda",
        name: "ALIADO ZOOM MBE CIUDAD OJEDA",
        address: "Av. Alonso De Ojeda, Edif. Tibidabo, P.b. Local 2, Sec. Casco Central, Ciudad Ojeda.",
        code: "706",
      },
      {
        id: "aA0zBlRXr4",
        city: "Ciudad Ojeda",
        name: "ZOOM CIUDAD OJEDA",
        address: "Sector Las Morochas, Av. Intercomunal Calle Cardon, Edificio Ojeda. Pb., Locales 6 Y 7.",
        code: "57",
      },
      {
        id: "aA0zBlRXr5",
        city: "El Venado",
        name: "ALIADO ZOOM INVERSIONES YENNY & ASOCIADOS C.A.",
        address: "Centro Comercial De Dos Plantas Vera Cruz Carretera Lara -zulia Local S/n P.b. Pasillo Principal No. 06,sector Casco Central.",
        code: "4056",
      },
      {
        id: "aA0zBlRXr6",
        city: "La Concepción",
        name: "ALIADO ZOOM INVERSIONES Y ENCOMIENDAS M Y G, C.A.",
        address: "Sector Los Lirios La Concepcion, (los Teques), Av. Principal, Local Nro. S/n.",
        code: "2350",
      },
      {
        id: "aA0zBlRXr7",
        city: "Machiques",
        name: "ALIADO ZOOM INVERSIONES Y COMERCIALIZADORA AJG 2022, C.A.",
        address: "Av Artes Entre Calle La Marina Y Calle El Carmen Casa Nro S/n, Machiques",
        code: "4025",
      },



      {
        id: "aA0zBlRXr8",
        city: "Maracaibo",
        name: "ALIADO ZOOM INVERSIONES ZULIMAR 05, C.A.",
        address: "Barrio San Trino La Pomona, Calle Nro. 102 Entre Av. Nro. 18 Y Calle Nro. 102a, Local Nro. 18-26.",
        code: "2718",
      },
      {
        id: "aA0zBlRXr9",
        city: "Maracaibo",
        name: "ALIADO ZOOM SULIM, C.A.",
        address: "Urb. Altos Del Sol Amado, Av.no. 75 Y Av. 75b , Casa No. 75b Casa, No. 75-44, Calle N°. 99 , Primera Etapa.",
        code: "2711",
      },
      {
        id: "aA0zBlRX10",
        city: "Maracaibo",
        name: "ALIADO ZOOM ARA EXPRESS, C.A.",
        address: "Av 58 CC Metrosol Nivel Pb Local 19-a Sector Circunvalacion Nro 2 Maracaibo.",
        code: "3063",
      },
      {
        id: "aA0zBlRX11",
        city: "Maracaibo",
        name: "ALIADO ZOOM ENVIOS 72 EXPRESS, C.A.",
        address: "Av 15 Las Delcias Con Calle 72 Cc Paseo 72 Nivel Pb Local Pb 06,sector Las Delicias.",
        code: "4063",
      },
      {
        id: "aA0zBlRX12",
        city: "Maracaibo",
        name: "ALIADO ZOOM GRUPO MAUCOVENCA, C.A.",
        address: "Sector Bella Vista, Calle Nro. 74, Con Av. Nro. 3y, Local Candeloro Nro. 5-a.",
        code: "2253",
      },
      {
        id: "aA0zBlRX13",
        city: "Maracaibo",
        name: "ALIADO ZOOM INVERSIONES 2 MRS, C.A.",
        address: "Av 4 Bella Vista Con Calle 64 Edif Vilmar Piso Pb Local Pb,sector Bella Vista.",
        code: "4018",
      },
      {
        id: "aA0zBlRX14",
        city: "Maracaibo",
        name: "ALIADO ZOOM INVERSIONES MARAEXPRESS, C.A.",
        address: "Av. 21, Esquina Con Calle 71, Local No. 1 Sector Indio Mara.",
        code: "2980",
      },
      {
        id: "aA0zBlRX15",
        city: "Maracaibo",
        name: "ALIADO ZOOM MBE 5 DE JULIO",
        address: "Av. 5 De Julio, Con Calle Av. 13-a, Centro Comercial Olimpico.",
        code: "704",
      },
      {
        id: "aA0zBlRX16",
        city: "Maracaibo",
        name: "ALIADO ZOOM MBE SANTA RITA",
        address: "Av. 8 Entre Calles 66a Y 67 Edif . El Globo Piso Pb Local 3 Sector Santa Rita.",
        code: "707",
      },
      {
        id: "aA0zBlRX17",
        city: "Maracaibo",
        name: "ALIADO ZOOM SERVICIOS DE ENTREGAS Y ENCOMIENDAS BRAVO C.A.",
        address: "Av 40 Local Nro 4 Urb La Coromoto Lote 1 Parcela 40 Zona 40 San Francisco.",
        code: "3314",
      },
      {
        id: "aA0zBlRX18",
        city: "Maracaibo",
        name: "ALIADO ZOOM SERVICIOS V V M, C.A.",
        address: "Calle 13 CC Oasis Nivel Pb Local L-3 Barrio Sierra Maestra Sierra Maestra.",
        code: "3269",
      },
      {
        id: "aA0zBlRX19",
        city: "Maracaibo",
        name: "ALIADO ZOOM WENDY INVERSIONES TECNO VENEZOLANAS, C.A.",
        address: "Calle 52-a Local Nro 1380000 Urb La Trinidad Sector Plaza De Toro.",
        code: "2068",
      },
      {
        id: "aA0zBlRX20",
        city: "Maracaibo",
        name: "ZOOM C.C AKRAI CENTER",
        address: "Calle 86 Pichincha Con Av 4 Bella Vista, Centro Comercial Akrai Center, Locales A-14 Y A-15 Pb.",
        code: "4036",
      },
      {
        id: "aA0zBlRX21",
        city: "Maracaibo",
        name: "ZOOM LA CHINITA",
        address: "Av. 15, Entre Calles 93 Y 95, Centro Comercial La Chinita, Primer Nivel, Local N° 26. P.ref. Por La Feria De Comida.",
        code: "168",
      },
      {
        id: "aA0zBlRX22",
        city: "Maracaibo",
        name: "ZOOM MARACAIBO",
        address: "Avenida 5 De Julio, Calle 77 Con Av. 12.",
        code: "82",
      },
      {
        id: "aA0zBlRX23",
        city: "Villa Del Rosario",
        name: "ALIADO ZOOM INVERSIONES MARTINEZ YBARRA, C.A.",
        address: "Sector Casco Central La Villa Del Rosario, Av. N°. 18 De Octubre, Local N°. 18-13.",
        code: "2052",
      },
    ]
  },
]